#### Name: Solutions

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [2]:
import numpy as np
import math
import statistics as stat

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [ ]:
#1
values = (2,3,4)
print values(2)
print values[3]

In [7]:
# solution

values = [2,3,4]
print(values[1])
print(values[2]) # element 3 was out of range, so printed 1 and 2 instaed (counting from 0)
# could also use values[-1] to print the last element 

3
4


#### Explanation: 

To define a list you must use square brackets. Then, since `print()` is a function, you must use parenthesis around what you want to print. Finally, to print one element of a list, square brackets `[]` must be used for the index

In [1]:
#2
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

TypeError: can't multiply sequence by non-int of type 'list'

In [1]:
# solution
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


#### Explanation: 

This person simply wanted to create a list that included all first names, to do this, you can just add the two lists together using a `+` and it will concatenate the lists

In [5]:
#3
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

NameError: name 'Arr1d' is not defined

In [4]:
# solution
arr1D = np.zeros([2,2], int)
arr1D[1,1] = 55
arr1D[0,0] = -999
print(arr1D)

[[-999    0]
 [   0   55]]


#### Explanation: 

First, I had to add the numpy import at the top of the notebook. THen, it is important to note that all variables are case sensitive. The A needs to be lowercase and the d needs to be uppercase. Finally, when using indices, we must make sure we don't try to call on an index beyond the array. I changed the 3,3 index (which doesn't exist) to 0,0

In [ ]:
#4
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

In [7]:
# solution
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


#### Explanation: 

When applying the `reshape()` function, you have to make sure you have when you multiple the rowsxcolumns that this matches the total number of elements in the original array. The original array is only 10 elements, so the reshape needs to be 5 rows by 2 columns rather than 5x3. 


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you will likely have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [8]:
s = "wooster physics" # defined variable 
print(s[0:4]) # prints out the first 4 elements, counting by 0

woos


#### explanation:

to get the first four characters, use indices 0:4, where index 4 (the 5th element) is not included

2. For the string s above, print out the last 4 characters

In [10]:
print(s[-4:]) # print end of variable 

sics


#### explanation:

When working from end of a list, use -# to go backwards (-1 is the last) and since the last index is not included, don't put a number. This means that `[-4:]` will go back to 4th from last element all the way to the end 

3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [15]:
my_list = [2.0, 4.0, 6.0, 8.0, 10.0] #define list
print(my_list)
my_list[2] = -10.0 # changes the 3rd element of the list 
print(my_list)


[2.0, 4.0, 6.0, 8.0, 10.0]
[2.0, 4.0, -10.0, 8.0, 10.0]


4. Create a numPy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [3]:
t = np.arange(0, 101, 5) # creates a 1D array that counts by 5 to 100
print(t)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [ ]:
# first create empty list
meas_list = []
print(meas_list)

# ask user for numbers to add to list
while len(meas_list) < 10:
    new_num = float(input("Please give a number between 1 and 10: "))
    if new_num > 0 and new_num <= 10: 
        meas_list.append(new_num)
    else: 
        print("the number must be between 1 and 10. Try again!")
print(meas_list)

# print length of list
print("the length of the list is ", len(meas_list))
    
# Convert to distance
v_mph = 55 # need to convert to m/s
v_m = v_mph*1609.34/3600

# Calculate stats
list_avg = sum(meas_list)/len(meas_list)
list_max = max(meas_list)
list_min = min(meas_list)

#print
print("The average, max, and min values of the list are:", list_avg, list_max, list_min)

#calculate distances
dist_avg = list_avg*v_m
dist_max = list_max*v_m
dist_min = list_min*v_m
print("The average, max, and min values of distance are:", dist_avg, ",", dist_max, ",", dist_min, "meters")


[]
the number must be between 1 and 10. Try again!
the number must be between 1 and 10. Try again!
[3.0, 9.0, 4.0, 9.0, 10.0, 2.0, 7.0, 9.0, 2.0, 5.0]
the length of the list is  10
The average, max, and min values of the list are: 6.0 10.0 2.0
The average, max, and min values of distance are: 147.52283333333332 , 245.87138888888887 , 49.174277777777775 , miles


In [16]:
## here is an alternative method if you read the directions as applying 55 to the entire 10 element list 
import operator
test_list = [2.0, 3.0, 6.0, 8.0, 9.0, 5.0, 3.0, 2.0, 7.0, 8.0]
K_list = [55] * len(test_list)
res = list(map(operator.mul, test_list, K_list))
print(res)
print("the average, max, and min values are: ", stat.mean(res), max(res), min(res))

[110.0, 165.0, 330.0, 440.0, 495.0, 275.0, 165.0, 110.0, 385.0, 440.0]
the average, max, and min values are:  291.5 495.0 110.0


#### Explanation:

For this problem, I decided that the best way to append 10 values from a user was to use a `while` loop. That way I did not need to put an input statement 10 times. By using the `len()` function, I could continue to append values to the list until it was 10 elements. 

From there, the `max()`, `min()`, and a combination of `len()` and `sum()` functions could be used on the lists and then I multiplied by the velocity (after converting it to m/s from mph)

### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic energy for different values of time 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Input a mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [ ]:
g = 9.81

#define height array 
height = np.arange(0,50.5,0.5)
print(height)

# input a mass
mass = 5.0 # kg 

# copy height array to create potential and kinetic arrays
potential = np.copy(height)
kinetic = np.copy(height)

#calculate potential energy
potential = potential*mass*g
print(potential)

#calculate kinetic energy 
kinetic = potential[-1]-kinetic*mass*g
print(kinetic)


# yes this makes sense. When the kinetic is max, the potential is zero. When the kinetic is 0, the potential is max

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]
What is the mass of the object? 5
[   0.      24.525   49.05    73.575   98.1    122.625  147.15   171.675
  196.2    220.725  245.25   269.775  294.3    318.825  343.35   367.875
  392.4    416.925  441.45   465.975  490.5    515.025  539.55   564.075
  588.6    613.125  637.65   662.175  686.7    711.225  735.75   760.275
  784.8    809.325  833.85   858.375  882.9    907.425  931.95   956.475
  981.    1005.525 1030.05  1054.575 1079.1   1103.625 1128.15  1152.675
 1177.2   1201

#### Explanation:
Remember to explain - see *Write a script 1* for example 

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [ ]:
# (a)
spinosaurus = np.arange(1,26).reshape(5,5) # create a 1D array with 25 elements and reshape to 2D 
spinosaurus[1:,:] -= 3 # subtract 3 from the bottom 4 rows 
# spinosaurus[1:5,:] -= 3 an alternative way to do this 
print("part a:")
print(spinosaurus)
print()

# (b) 
print("part b:") 
print(spinosaurus[2]) # if you use only the first index, it gives the row
#print(spinosaurus[2,:]) # could also do it this way 

# (c)
print("part c:")
print(spinosaurus[:,2]) # printing all rows of the third column, which is the 2nd element 

#(d)
mini_spinosaur = np.copy(spinosaurus[1:3,2:4]) # using np.copy to make a copy of an array with certain elements only 
print("part d:")
print(mini_spinosaur)
#spinosaurus[2,2] = -99
#print(spinosaurus)
#print(mini_spinosaur)

#(e)
mini_spinosaur **= 2 #app
print(mini_spinosaur)

part a:
[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]

part b:
[ 8  9 10 11 12]
[ 8  9 10 11 12]
part c:
[ 3  5 10 15 20]
part d:
[[ 5  6]
 [10 11]]
[[ 25  36]
 [100 121]]


#### Explanation:
 
    Write something short! 