#### Name: 

In [ ]:
Juno Ryan

### <font color='red'> Comments </font> 

<font color='red'> Just double-click on the Name cell and enter your name after Name:</font> 


# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [1]:
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [1]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (172649615.py, line 3)

In [2]:
values = (2,3,4)
print(values[2])
print(values[0])

4
2


In [ ]:
print(type(values)) # Dr. DeGroot checking on the type of your variable 

<class 'tuple'>


Corrections: A few things wrong here. First misuse of parentheses and brackets. Print needs parentheses and the list index needs brackets. Second, since list indices are counted from 0, there is no index 3.

### <font color='red'> Comments </font> 

<font color='red'> Almost! since it says that want to define it as a list, need to switch the definition of values to be brackets: 

values = [2,3,4]

otherwise it's a tuple, which is not what we want. </font> 


In [4]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

TypeError: can't multiply sequence by non-int of type 'list'

In [13]:
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)
#or
nums_a = np.array([2, 3, 4, 5],int)
nums_b = np.array([6, 7, 8, 9],int)
nums = nums_a * nums_b
print(nums)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']
[12 21 32 45]


Correction: You can't multiply lists. You can add lists, which concatenates them as shown. If you really want to multiply, you can multiply two arrays of integers (or floats) which multiplies the first number by the first number and so on.

### <font color='red'> Comments </font> 

<font color='red'> What is your 'or' here with the arrays? says specifically want to make a combined list of first names, i don't understand your second part? just to show array multiplication? not necessary here </font> 


In [7]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

NameError: name 'Arr1d' is not defined

In [17]:
arr1D = np.zeros([2,2], int)
print(arr1D)
arr1D[1,1] = 55
arr1D[0,0] = -999
print(arr1D)

[[0 0]
 [0 0]]
[[-999    0]
 [   0   55]]


Correction: First, there are some capitilization issues. Second, the array is 2 by 2, so the maximum index in the bottom right corner is [1,1]. There is no [2,2] index due to python starting from 0. I have printed out the arrays to demonstarate this.

### <font color='red'> Comments </font> 

<font color='red'> had also not imported numpy, but you had added numpy before this so didn't catch that </font> 


In [18]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [19]:
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


Correction: When reshaping an array you have to make it into a valid shape. An array of length 10, which first_arr is, cannopt be shaped into a 5x3 array, which would have to be of length 15. Instead I have shaped it into a 5x2 array.

### <font color='red'> Comments </font> 

<font color='red'> good! </font> 


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [20]:
s = 'wooster physics'
print(s[:4]) #[:4] prints out the indices of the string up to but not including 4

woos


2. For the string s above, print out the last 4 characters

In [22]:
s_len = len(s)
last_4 = len(s) - 4
print(s[last_4:])

sics


### <font color='red'> Comments </font> 

<font color='red'> good, but could make it easier on yourself by using negative numbers: 

s[-4:] </font> 


Because I hate counting I have written code to determine the index of the fourth to last letter in 'wooster physics' by finding the length and subtracting 4. I then print that letter and every letter after it using [last_4:]

3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [23]:
pos_list = [1.0,2.0,3.0,4.0,5.0]
print(pos_list)
pos_list[2] = -10.0 #replace third value
print(pos_list)

[1.0, 2.0, 3.0, 4.0, 5.0]
[1.0, 2.0, -10.0, 4.0, 5.0]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [26]:
t = np.arange(0,101,5,int) #prints 0 to 101 counting by 5's so 100 is included
print(t)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### <font color='red'> Comments </font> 

<font color='red'> great job! </font> 


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [33]:
meas_list = []
counter = 0
new_num = 0
#Asks for 10 inputs
while counter < 10:
    new_num = int(input("Input a number between 1 and 10"))
    meas_list.append(new_num)
    counter += 1
#Prints list statistics
print(len(meas_list))
avg_meas = sum(meas_list)/len(meas_list)
max_meas = max(meas_list)
min_meas = min(meas_list)
print(avg_meas)
print(max_meas)
print(min_meas)
#Convert mph to m/s
meters_per_mile = 1609.34
seconds_per_hour = 3600
speed_ms = 55 * meters_per_mile / seconds_per_hour
#Calculate and print distances
avg_dist = avg_meas * speed_ms
max_dist = max_meas * speed_ms
min_dist = min_meas *speed_ms
print("Average distance is", round(avg_dist,2), "m")
print("Maximum distance is", round(max_dist,2), "m")
print("Minimum distance is", round(min_dist,2), "m")

Input a number between 1 and 10 9
Input a number between 1 and 10 8
Input a number between 1 and 10 7
Input a number between 1 and 10 5
Input a number between 1 and 10 3
Input a number between 1 and 10 2
Input a number between 1 and 10 1
Input a number between 1 and 10 9
Input a number between 1 and 10 8
Input a number between 1 and 10 5


10
5.7
9
1
Average distance is 140.15 m
Maximum distance is 221.28 m
Minimum distance is 24.59 m


I used a while list with an increasing counter to ask for 10 values between 1 and 10. I then print the length of the list and it's average, maximum, and minimum using built in functions. I then convert 55 mph to m/s and calculate and print the corresponding distances. When printing the distances I rounded to two decimal places.

### <font color='red'> Comments </font> 

<font color='red'> nice job! for your while statement, could use len() of instead of a counter to keep track of your while statement, also might want an if staetment to check if it is a number and if it is between 1 and 10</font> 


### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [38]:
heights = np.arange(0,50.5,0.5,float) #0 to 50 counting by 0.5 inclusive
mass = 5
g = 9.8
v=np.sqrt(2*g*(50-heights)) #calculates velocity using v^2 = v0^2 + 2ax
T = (1/2)*mass*(v**2) #calculates KE using T = (1/2)mv^2
U = mass*g*heights #calculates PE using U = mgh
print(heights)
print(U)
print(T)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]
[   0.    24.5   49.    73.5   98.   122.5  147.   171.5  196.   220.5
  245.   269.5  294.   318.5  343.   367.5  392.   416.5  441.   465.5
  490.   514.5  539.   563.5  588.   612.5  637.   661.5  686.   710.5
  735.   759.5  784.   808.5  833.   857.5  882.   906.5  931.   955.5
  980.  1004.5 1029.  1053.5 1078.  1102.5 1127.  1151.5 1176.  1200.5
 1225.  1249.5 1274.  1298.5 1323.  1347.5 1372.  1396.5 1421.  1445.5
 1470.  1494.5 1519.  1543.5 1568.  1592.5 1617.  1641.5 166

These arrays look like I would expect. Potential energy starts at 0 and increases, kinetic energy starts high and decreases to 0. At all points T+U = constant.

### <font color='red'> Comments </font> 

<font color='red'> Could use some comment about what your variables m and g are -> also comment on variables </font> 


### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [54]:
spinosaurus = np.array(np.arange(1,26,1,int),int).reshape(5,5)
spinosaurus[1:,:] -= 3
print(spinosaurus)
print(spinosaurus[2,:]) #print middle row
print(spinosaurus[:,2]) #print 3rd column
mini_spinosaur = spinosaurus[1:3,2:4] #create mini
print(mini_spinosaur)
mini_spinosaur = mini_spinosaur**2 #square mini
print(mini_spinosaur)

[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]
[ 8  9 10 11 12]
[ 3  5 10 15 20]
[[ 5  6]
 [10 11]]
[[ 25  36]
 [100 121]]
[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]


I created spinosaur by creating an array of the numbers 1 through 25 and then reshaped it into a 5 by 5 array. I then subtracted 3 from every column in every row except the first row. To create mini_spinosaur I sliced only the 2nd through 4th rows and 3rd through 5th columns.

### <font color='red'> Comments </font> 

<font color='red'> Nice job. make sure to use np.copy() for creating anew array as a subset as another array. Otherwise, any changes you make to the original array will change your subset too. 

Could use a few more comments in your codes. Always comment on varialbes, and give a quick definition of what you're doing </font> 
