#### Name: <font color='red'> **hopefully** Wesley Lindelow</font> 


### <font color='red'> Comments </font> 

<font color='red'> I need you to put your name here so I am always confident that I'm grading the correct lab</font> 


# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [1]:
import math
import numpy as np
import time

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [1]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (172649615.py, line 3)

The 'print' command requires parentheses around whatever is to be printed, which is absent in the original code. Parentheses were used instead of a square bracket when calling the 'values' list. The index number for a list starts at zero, so the original code input index numbers one greater than required when calling for elements of the list.

### <font color='red'> Comments </font> 

<font color='red'> you mention the issue of parenthses in stead of brackets in calling the list, but you don't correct it. To define a list, we need to use brackets. Parentheses define a tuple, which we don't want. Need:

values = [2,3,4]</font> 


In [13]:
values = (2,3,4)
print(values[1])
print(values[2])

3
4
(2, 3, 4)


In [11]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

TypeError: can't multiply sequence by non-int of type 'list'

Addition should be used instead of multiplication when combining two lists in this way.

In [12]:
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [23]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

NameError: name 'Arr1d' is not defined

The name of the array being defined is not kept consistent. Without the NumPy library imported, the array commands do not work. This code also uses np as an alias for NumPy, so that also needs to be defined when importing it. To illustrate this, I included the 'import' command in the revised code, even though it's set up already earlier in the document. The original code attempts to change a value outside of the defined bounds of the array, and like lists, array indices start at zero, not one.

In [28]:
import numpy as np
arr1D = np.zeros([2,2], int)
arr1D[0,0] = 55
arr1D[1,1] = -999

In [29]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

ValueError: cannot reshape array of size 10 into shape (5,3)

When reshaping an array, the size of the array/number of elements cannot change. The original code attempts to reshape an array with 10 elements into one with 15, which causes it to fail to reshape the array.

In [30]:
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


### <font color='red'> Comments </font> 

<font color='red'> good! </font> 


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [31]:
s = 'wooster physics'
s_b = list(s)
print(s_b[0], s_b[1], s_b[2], s_b[3]) 

w o o s


### <font color='red'> Comments </font> 

<font color='red'> use a range of indices to make this easier on yourself: 

s[0:4]</font> 


2. For the string s above, print out the last 4 characters

In [34]:
s = 'wooster physics'
s_b = list(s)
print(s_b[11], s_b[12], s_b[13], s_b[14])

s i c s


### <font color='red'> Comments </font> 

<font color='red'> Instead, use indices: 

s[-4:]</font> 


The list also includes the space between the words, so I had to take that into account to not call incorrect elements of the list.

3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [2]:
floats: list[float] = [10, 8, 6, 4, 2]
print(floats)
floats[2] = -10
print(floats)

[10, 8, 6, 4, 2]
[10, 8, -10, 4, 2]


In [3]:
print(type(floats[0]))

<class 'int'>


The list has to be a list (using square brackets), not a tuple (using parentheses), since tuples aren't alterable.

### <font color='red'> Comments </font> 

<font color='red'> this is a very confusign format, not what we have done in class. for yoru list, instead should just have it be: 

my_list = [10.0, 8.0, 6.0, 4.0, 2.0]

you actually still have a list of integers, not float values </font> 


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [42]:
import numpy as np
t = np.arange(5, 100, 5)
print(t)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


### <font color='red'> Comments </font> 

<font color='red'> only need to import numpy once in your program. supposed to include 0 and 100, so need arange to go from 0 to 101 to have this work. 

t = np.arange(0,101,5) </font> 


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [56]:
meas_list: list[float] = []
i = 0
while i < 10:
    meas_list.append(float(input('Input a number from 1 to 10:')))
    i += 1
print('Length:', len(meas_list))
print('Mean:', sum(meas_list) / len(meas_list))
print('Maximum:', max(meas_list))
print('Minimum:', min(meas_list))
print('Mean Distance:', 55 * sum(meas_list) / len(meas_list))
print('Max Distance:', 55 * max(meas_list))
print('Min Distance:', 55 * min(meas_list))

Length: 10
Mean: 5.5
Maximum: 10
Minimum: 1
Mean Distance: 302.5
Max Distance: 550
Min Distance: 55


Script creates an empty list of floats, then requests ten numbers to append to the empty list. The required mathematical operations are done within the 'print' commands to save space.

### <font color='red'> Comments </font> 

<font color='red'> I strongly discourage defining a list like that: 

meas_list: list[float] = [] 

I don't think it's accomplishing what you think. Instead, a blank list is just: 

meas_list = []



In while statement should include some if/else statement to check if input is between 1 and 10 (and if its a number)


55 is in units of mph and distance is supposed to me in meters</font> 


### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [69]:
import numpy as np
y_arr = np.arange(0, 50.5, 0.5)
u_arr = []
k_arr = []
m = 1
i = 0
e_tot = m * 9.81 * 50 

while i < 101:
    u_arr.append(float(round(m * 9.81 * y_arr[i], 3)))
    k_arr.append(float(round(e_tot - u_arr[i], 3)))
    i += 1

print('Height:', y_arr)
print('Kinetic Energy:', k_arr)
print('Potential Energy:', u_arr)

Height: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]
Kinetic Energy: [490.5, 485.595, 480.69, 475.785, 470.88, 465.975, 461.07, 456.165, 451.26, 446.355, 441.45, 436.545, 431.64, 426.735, 421.83, 416.925, 412.02, 407.115, 402.21, 397.305, 392.4, 387.495, 382.59, 377.685, 372.78, 367.875, 362.97, 358.065, 353.16, 348.255, 343.35, 338.445, 333.54, 328.635, 323.73, 318.825, 313.92, 309.015, 304.11, 299.205, 294.3, 289.395, 284.49, 279.585, 274.68, 269.775, 264.87, 259.965, 255.06, 250.155, 245.25, 240.345, 235.44, 230.535, 225.6

Arrays look as expected, with kinetic energy being greatest at 0 m and potential energy being greatest at 50 m. Rounded the calculated values to three decimal places to make printing them out more compact.

Script sets up initial array and variables required, along with an index variable and two empty arrays to fill later. Mass is assumed to be 1 kilogram here for simplicity. The potential and kinetic energy is calculated for each height and appended to the corresponding empty array defined earlier. Calculated values of kinetic and potential energy are rounded to three decimal places, since otherwise those arrays would take up much more space. The values appended to those arrays must be converted into floats, since otherwise they will default to np.float64() values, which makes the arrays more difficult to read when printed.

### <font color='red'> Comments </font> 

<font color='red'> good </font> 


### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [1]:
import numpy as np
flatpack_spino = np.array([1, 2, 3, 4, 5, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])
spinosaurus = flatpack_spino.reshape(5, 5)
mini_spinosaur = spinosaurus[1:3, 2:4]
mini_spino_sqr = mini_spinosaur ** 2

print(spinosaurus[2])
print(spinosaurus[0:5, 2])
print(mini_spinosaur)
print(mini_spino_sqr)

[ 8  9 10 11 12]
[ 3  5 10 15 20]
[[ 5  6]
 [10 11]]
[[ 25  36]
 [100 121]]


Script creates a 1D array containing all of the required values, then reshapes it into the desired 2D 'spinosaurus' array. Four of the values in that array are sliced from it and used to define the 'mini_spinosaur' array. Each value in this new array is then squared to define yet another array. The program then prints out the third row and column from the original spinosaurus array, the 'mini_spinosaur' array, and the squared 'mini_spinosaur' array.

### <font color='red'> Comments </font> 

<font color='red'> you have missed most of the points of this problem. 

Would be great to find a way to define first array with mathematics in arrays rather than manually -> can you think of how? 

for mini-spinosaur, you are dreating a subset, so should make a copy of a subset using np.copy and indices

no comments in code </font> 
