#### Name: Ben Maxwell

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [9]:
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [1]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (172649615.py, line 3)

#1 Explanation:
The first mistake I notice is that the items that are meant to be printed are not in parenthesis, so that is the first thing I fixed. The second mistake is that the values(2) is attempting to call upon the 2nd value, however it should be using square brackets [] instead of parenthesis (). The final mistake that I notice is the values it is calling upon. It calls upon values[2] and values[3], which I assume is meant to be the 2nd and 3rd term. However the 2nd term is found by using values[1] and the 3rd term is found using values[2], so I fixed this accordingly. 

In [5]:
#1 Ben's Version - define & index specific elements of a list
values = (2,3,4)
print(values[1])
print(values[2])

3
4


In [6]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

TypeError: can't multiply sequence by non-int of type 'list'

#2 Explanation
For some reason, the code is attempting to multiply two lists. However, to create a single list with all the first names, one just needs to add the lists (using +).

In [7]:
#2 Ben's Version - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [8]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

NameError: name 'np' is not defined

#3 Explanation
The first mistake I find is that it calls upon Arr1d, which is not defined (Notice the capitals, it should be arr1D). The second thing I noticed was that the array is a 2 by 2 array, and the code is attemptig to call upon the values in the top left and bottom right spaces. However, the mistake is that 1,1 is not the top left, and instead the bottom right position, so I redefined is as [0,0]. Then, 3,3 is not even a spot within the array, so I redefined as [1,1]. (I also made it to print the array so I could check my answer.)

### <font color='red'> Comments </font> 

<font color='red'> Think you also had to add the numpy import at the top </font> 


In [13]:
#3 Ben's Version- define array annd change certain values 
arr1D = np.zeros([2,2], int)
arr1D[0,0] = 55
arr1D[1,1] = -999
print(arr1D)

[[  55    0]
 [   0 -999]]


In [ ]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

#4 Explanation
The big (and only) mistake I notice is that when reshapeing the array which includes 10 terms, the reshape line is attempting to reshape it into an array with 5x3 terms which is too large. To fix this, I just changed the 2 to a 3, making it a 5x2 array. 

In [15]:
#4 Ben's Version- reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


### <font color='red'> Comments </font> 

<font color='red'> Good job!  </font> 


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [1]:
# Defining string variable
s = "Wooster Physics"
# Take the first 5 letters
s_first_five = s[:5]
# Printing!
print(s_first_five)

Woost


#1 Explanation
I began by defining the given string "Wooster Physics". Then, I used google for advice on the next line. I learned that I can create a new string while using the square brakets like the previous string was a list, making each letter a term in the list. Then, I call upon this "list" for the first 5 terms by putt :5 in the brackets, which is calling upon all terms before [5] (remember the first 5 terms are [0] - [4]). Then I printed my new string. 

### <font color='red'> Comments </font> 

<font color='red'>we did talk about indexing in class, which works for strings just like any other array. however, the problem says to print out the first 4 characters and you have done the first 5?</font> 


2. For the string s above, print out the last 4 characters

In [2]:

# Take the first 5 letters
s_last_four = s[-4:]
# Printing!
print(s_last_four)

sics


#2 Explanation
I used google for advice. I learned that by putting a negative before the value, the number is instead "counting backwards" in the list as opposed to forwards (if that make sense, the s[-3] value is i for example). The : takes all values after the [-4] value, which in this case is [-4] - [-1]. Then I printed my new string, which was pretty sic (s). 

### <font color='red'> Comments </font> 

<font color='red'> when I first looked at this, there was an extra s underneath your `sics`. Now that I re-ran is, it disappeared. confusing</font> 


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [ ]:
#Defining a List with 5 different positive float values
i_am_a_list = [1.1, 1.5, 4.5, 3.7, 567389.565789]
print(i_am_a_list)
# Redefining the 3rd value as -10
i_am_a_list[2] = -10
print(i_am_a_list)

[1.1, 1.5, 4.5, 3.7, 567389.565789]
[1.1, 1.5, -10, 3.7, 567389.565789]


I began by making a list with 5 positive float values as instructed. Then, after printing the list to make sure it is real, I redefined the 3rd term to be -10 (by using i_am_a_list[2]).

4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [27]:
#Creating a numpy array called t
t = np.arange(0,101,5,float)
print(t)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


I created the array using the code above, using np.arrange to create the array, 0 to define the starting number, 101 to define the ending number (which is 101 to include 100), and finally defining 5 to count by 5s (I also defined that these should be floats).

### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [35]:
#Defining a list
meas_list = []
#Asking the user for a value 10 times and adding them to the list
n=0
while n<10:
    meas_list.append(int(input("Give me a number between 1 and 10")))
    n=n+1
#Pringint Results
print(meas_list)
#Calculating Avg, Min, and Max
meas_list_avg = sum(meas_list)/len(meas_list)
meas_list_max = min(meas_list)
meas_list_min = max(meas_list)
#More Printing!
print(meas_list_avg)
print(meas_list_max)
print(meas_list_min)

[1, 1, 2, 2, 3, 3, 4, 4, 5, 5]
3.0
1
5


I began by defining an empty list named meas_list. I the made use of a while loop to ask the user for a number between 1-10, ten times. I made sure this value was an integer, and appended these values to the list as they were added. To keep track of how many times the question was asked, I defined a variable n as 0, and increased by 1 for every time the loop ran. Once n=10, the loop stopped. Then, I printed the list to check my results. Once completed, I used the sum and len commands to calculate the avg, (which is found using avg=sum/len), and then found the min and max using the min and max commands. I then printed my results. 

### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [51]:
#Array of Heights from 0 to 50m counting by 0.5m
heights = np.arange(0,50.1,0.5,float)
#Asking The user for a mass
mass = float(input("What is the mass of your object in kg"))
#Calculating array of potential at each height
potential = heights*10.*mass
#Calculating array of kinetic at each height
kinetic = 0.5*mass*(2.*10*(50-heights))
#Printing!
print(heights)
print(potential)
print(kinetic)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]
[   0.   25.   50.   75.  100.  125.  150.  175.  200.  225.  250.  275.
  300.  325.  350.  375.  400.  425.  450.  475.  500.  525.  550.  575.
  600.  625.  650.  675.  700.  725.  750.  775.  800.  825.  850.  875.
  900.  925.  950.  975. 1000. 1025. 1050. 1075. 1100. 1125. 1150. 1175.
 1200. 1225. 1250. 1275. 1300. 1325. 1350. 1375. 1400. 1425. 1450. 1475.
 1500. 1525. 1550. 1575. 1600. 1625. 1650. 1675. 1700. 1725. 1750. 1775.
 1800. 1825. 1850. 1875. 1900. 1925. 1950. 1975.

I began by defining an array of heights from 0m to 50m, going up by 0.5m at every value (being to have the second value be 50.1 as to include 50, and also to define it as a float). Then, I used an input to ask the user for a mass in kg. Next, I calculated the potential energy using the formula $p_e=mgh$ where $p_e$ is potential energy, $m$ is the mass (given by user) $g$ is gravity ($10 m/s^2$) and $h$ is the height of the object at a specific height (given by our array of heights). By using this equation, it creates an array of all of the potential energies of an object at the given heights wihtin the array. I then calculated the kinetic energy using the equation $k_e = \frac{1}{2}mv^2$ where $k_e$ is the kinetic energy, $m$ is the mass (given by the user), and $v$ is velocity at a specifc point. The velocity at a certain point can be found usig the equation $v^2=V_0^2+2ax$. $V_0$ is initial velocity, which is 0 $m/s^2$, a is acceleration from gravity ($10 m/s^2$), and x is the distance the object has traveled (which in this case is 50m minus the array of heights.) Using these equations, we are then given an array of all the kinetic energies of the object at a specifc height (given by our array of heights.) The I printed all of my results

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [78]:
#Making My Array
spinosaurus = np.arange(-2,23,1).reshape(5,5)
#Making My Array have correct numbers
spinosaurus[0]=spinosaurus[0]+3
print(spinosaurus)
#Printig the Middle Row
print(spinosaurus[2])
#Printing the Middle Column
print(spinosaurus[:,2])
#Defining and printing a new array
mini_spinosaurus = np.arange(5,9,1).reshape(2,2)
mini_spinosaurus[1]=mini_spinosaurus[1]+3
print(mini_spinosaurus)
#Squaring every element of new array
mini_spinosaurus = mini_spinosaurus**2
print(mini_spinosaurus)



[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]
[ 8  9 10 11 12]
[ 3  5 10 15 20]
[[ 5  6]
 [10 11]]
[[ 25  36]
 [100 121]]


I start out by making the array spinosaurus. I do this making an array that goes from -2 t0 23 by 1, in a 5x5 grid. Then, to fix the first row I added the entire row by 3. I then printed the middle row by calling upon it using square brakets []. I then printed the middle/3rd column by using [:,2], which calls upon the third column. Next, I created a new array called mini spinosaurus, which I made in a very similar way to the first (5 to 9 by 1s, in a 2x2, fixed second row by adding 3). Finally, I squared  mini-spinosaurus by squaring the entire array.

### <font color='red'> Comments </font> 

<font color='red'> would ideally use np.copy() and indexing to make the mini-spinosaur array since creating a subset </font> 
