#### Name: Tim Book

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)


#### Start by importing any packages you need below (feel free to update as you go):

In [33]:
import math
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [1]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (172649615.py, line 3)

Lists must be defined with square brackets. Print requires parentheses. Print(values(2)) makes no sense since indexes must be called using square brackets. Calling index 3 in line 4 will return an error since 3 is out of the range of the list. Given that this is an error we can assume line 3 was meant to call index 1. 

In [5]:
values = [2,3,4]
print(values[1])
print(values[2])

3
4


In [6]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

TypeError: can't multiply sequence by non-int of type 'list'

The concatination opperator for lists is "+" not "*".

In [7]:
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [8]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

NameError: name 'np' is not defined

Numpy was never imported. Python is case sensitive; Arr1d and arr1d are not the same. This is a 2D array so 1D is a bad name, but not technically an error. Line 3 edits row 2, collumn 2 (index 1,1), and line 4 edits a row and collumn out of the array. I will be changing line 3 to edit row 1, collumn 1 (index 0,0) and line 4 to edit row 2, collumn 2 (index 1,1). 

In [14]:
import numpy as np
arr1D = np.zeros([2,2], int)
arr1D[0,0] = 55
arr1D[1,1] = -999
print(arr1D)

[[  55    0]
 [   0 -999]]


In [15]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

ValueError: cannot reshape array of size 10 into shape (5,3)

20 elements can not be split into 5 rows and 3 collumns. Let us instead reshape this to a 5,2 array. Another way to fix this would be to add 10 zeros to the end of the array and then reshape. 

In [16]:
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


### <font color='red'> Comments </font> 

<font color='red'> great job!  </font> 


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [18]:
s = 'wooster physics'
print(s[0],s[1],s[2],s[3])

w o o s


### <font color='red'> Comments </font> 

<font color='red'> could do this more easily with just `s[0:4]` </font> 


2. For the string s above, print out the last 4 characters

In [19]:
print(s[-4],s[-3],s[-2],s[-1])

s i c s


### <font color='red'> Comments </font> 

<font color='red'> same, coud instead do `s[-4:]`</font> 


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [20]:
positives = [1.0,2.0,3.0,4.0,5.0]
print(positives)
positives[2] = -10.0
print(positives)

[1.0, 2.0, 3.0, 4.0, 5.0]
[1.0, 2.0, -10.0, 4.0, 5.0]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [31]:
t = np.arange(0,101,5)
print(t)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
Python 3.11.5


### <font color='red'> Comments </font> 

<font color='red'> great! </font> 


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [38]:
meas_list=[]
counter = 0
while counter < 10:
    temp = [int(input("Please input a time from 1-10 hours."))]
    meas_list=meas_list + temp
    counter = counter + 1
print(meas_list)
print("The length is", len(meas_list))
total = sum(meas_list)
average=total/len(meas_list)
print("The average is",average)
print("The highest value is", max(meas_list))
print("The lowest value is", min(meas_list))
distance = (np.array(meas_list))*55*1609.34
print("The distances traveled for each of these times of an object moving at 55 mph are:", distance)

Please input a time from 1-10 hours.1
Please input a time from 1-10 hours.2
Please input a time from 1-10 hours.3
Please input a time from 1-10 hours.4
Please input a time from 1-10 hours.5
Please input a time from 1-10 hours.6
Please input a time from 1-10 hours.7
Please input a time from 1-10 hours.8
Please input a time from 1-10 hours.9
Please input a time from 1-10 hours.10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The length is 10
The average is 5.5
The highest value is 10
The lowest value is 1
The distances traveled for each of these times of an object moving at 55 mph are: [ 88513.7 177027.4 265541.1 354054.8 442568.5 531082.2 619595.9 708109.6
 796623.3 885137. ]


We start with an empty list to append values to. We also introduce a counter to memory so we can track how many things are within the list. The list is then appended to as many times as the counter incraments (in this case it goes to 10). The average is taken with the sum of the list divided by its length, and the min and max are calculated using other functions native to python. The distance is calculated by converting the list to an array for ease of calculation and scaling the whole list by 55x1609.34. 

### <font color='red'> Comments </font> 

<font color='red'> great! nice job remembered to convert units too!  but you need to include comments in code</font> 


# Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [43]:
heights = np.arange(0,51,0.5)
mass = 10
PE = heights*mass*9.8
E_Max = PE[-1]
KE = E_Max - PE
print(heights)
print(PE)
print(KE)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50.  50.5]
[   0.   49.   98.  147.  196.  245.  294.  343.  392.  441.  490.  539.
  588.  637.  686.  735.  784.  833.  882.  931.  980. 1029. 1078. 1127.
 1176. 1225. 1274. 1323. 1372. 1421. 1470. 1519. 1568. 1617. 1666. 1715.
 1764. 1813. 1862. 1911. 1960. 2009. 2058. 2107. 2156. 2205. 2254. 2303.
 2352. 2401. 2450. 2499. 2548. 2597. 2646. 2695. 2744. 2793. 2842. 2891.
 2940. 2989. 3038. 3087. 3136. 3185. 3234. 3283. 3332. 3381. 3430. 3479.
 3528. 3577. 3626. 3675. 3724. 3773. 3822. 

These arrays could look better. I'm not quite sure how to get them all into one array aligned vertically (I tried using np.transpose() and np.concatenate((a,b),axis=c).

### <font color='red'> Comments </font> 

<font color='red'> good! but missing comments in code and markdown doens't explain process along with your commenting on results </font> 


### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [47]:
spinosaurus = np.array([[1,2,3,4,5],[3,4,5,6,7],[8,9,10,11,12],[13,14,15,16,17],[18,19,20,21,22]])
print(spinosaurus[2])
print(spinosaurus[:,2])
mini_spinosaur = np.array([[spinosaurus[1,2],spinosaurus[1,3]],[spinosaurus[2,2],spinosaurus[2,3]]])
print(mini_spinosaur*mini_spinosaur)

[ 8  9 10 11 12]
[ 3  5 10 15 20]
[[ 25  36]
 [100 121]]


For this problem, I defined the rows of the np array. Rows can be printed by indexing to the row -1. Columns can be printed by using :, and whatever column you're indexing to -1. Mini spinosaur was created by taking the indexes of the values in spinosaurus and calling the values at those locations. Mini spinosaur was squared by multiplying it with itself. 

### <font color='red'> Comments </font> 

<font color='red'> there is a much more elegant way to define original array. Try to find out how rather than hand typing it all 

same with part (d) - easier way to make this subset 

okay though! do need comments in code </font> 
