#### Name: Sutton Ursillo

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [1]:
import math as m
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [11]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (172649615.py, line 3)

for a list it needs to be in brackets like [2,3,4]. It has the wrong number for the print function, it starts at zero so it should be values[2]. and to get the value it should not be in () as well. 

In [ ]:
values = [2,3,4]
print(values[1])
print(values[2])
print(type(values))

3
4
<class 'list'>


In [ ]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

you cannot multiply the lists together when they are non-int type of lists. it needs to be addition

In [ ]:
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [ ]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

there is 2 typo's with Arr1d it should be arr1D (case sensitive). Also [3,3] does not exist, should be [1,1] if we are trying to get the bottom right corner and [0,0] if we want to put 55 in the top right. 

In [ ]:
arr1D = np.zeros([2,2], int)
arr1D[0,0] = 55
arr1D[1,1] = -999
print(arr1D)

[[  55    0]
 [   0 -999]]


### <font color='red'> Comments </font> 

<font color='red'> Also had to import numpy at the top, but maybe you auto did that when you opened the notebook </font> 


In [ ]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

the 2D array we are trying to shape this into is too big for the array that is given. should change it into (5,2).

In [ ]:
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


### <font color='red'> Comments </font> 

<font color='red'>  great job! </font> 


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [ ]:
s = 'wooster physics'
print(s[:4])

woos


2. For the string s above, print out the last 4 characters

In [ ]:
print(s[11:])

sics


### <font color='red'> Comments </font> 

<font color='red'> CAn also use negative indices to accomplish this if you don't want to count: 

s[-4:]</font> 


So it depends where the ':' is. for this last one I told it to ignore the first 11 characters and print the last 4. 

3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [ ]:
list_1 = [1,2,3,4,5, float]
print(list_1)
list_1[2] = -10
print(list_1)

[1, 2, 3, 4, 5, <class 'float'>]
[1, 2, -10, 4, 5, <class 'float'>]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [ ]:
t = np.arange(0,105,5, float)
print(t)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


### <font color='red'> Comments </font> 

<font color='red'> excellent!  </font> 


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [ ]:
meas_list = [] #creating a empty list 
i = 0 # defining i
while i < 10: # the user input is less than 10 values
    value = float(input(f"enter number {i+1}: ")) #found some nice tips on how to do this from geeksforgeeks.org
    meas_list.append(value) # appending the user input
    i += 1 # adding 1 to the value of i
print(len(meas_list))
print(meas_list)

average = sum(meas_list)/len(meas_list)
print(average)
max_value = max(meas_list) # using pythons built in functions
print(max)
min_value = min(meas_list)
print(meas_list)


meas_list *= 55
print(meas_list)


10
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0]
4.6
<built-in function max>
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0]
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0, 1.0, 2.0, 3.0, 4

This is where I stopped. There are a couple of problems with the code. it does not like the max function (i thought that was built in) and I don't think the lat two lines are correct. I think i have to do a while loop for that. 

### <font color='red'> Comments </font> 

<font color='red'> It looks like the max function is working but you are printing max rather than the variable max_value. 

for distance, it was supposed to be in meters, and you are multiplying by 55 mph. 

for your loop, need to ask for a number specifically between 1 and 10 (never say those words), and would be good to have some kind of check that it is a number and between that range

comments in second half of code are lacking </font> 


### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

### <font color='red'> Comments </font> 

<font color='red'> oh no, I would hope you would have at least gotten to this one. Try to work a little faster in lab. 

should go back and do this and the next one so you are comfortable with arrays</font> 


### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.