#### Name: Kristen Townsend

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [4]:
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [ ]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

Oh my goodness! Brackets aren't the same as parentheses in coding! Silly Dr. DeGroot.\
Because values is a list, all of the elements must be inside brackets. However, print is a function and uses parentheses!\
One more thing, when indexing a list, you need to use brackets instead of parentheses. One is right, so close! Also, because indexing begins with $0$ instead of $1$, I can only assume you meant to index values\[$1$\] and values\[$3$\].

In [2]:
values = [2,3,4]
print(values[1])
print(values[2])

3
4


In [ ]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

Oh, dear! You can't multiply lists to concatenate them! Silly Dr. DeGroot.\
To make a list of all the names, all you need to do is add \(+\) the lists together.

In [3]:
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [ ]:
#3 - define array and change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

My word! Spelling mistakes and indexing out of range? Silly Dr. DeGroot.\
First up, I need to import numpy so this array can be defined. Next, Arr1d is not the same as arr1D! Capitals are important in the world of code.\
\[3,3\] is so far out of range, I don't even know what you want me to change! So I'm going to delete it! It is no longer real.

In [6]:
arr1D = np.zeros([2,2], int)
arr1D[1,1] = 55

print(arr1D)

[[ 0  0]
 [ 0 55]]


In [ ]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

Great Heavens! Trying to reshape an array where you don't have enough elements to fill it? Silly Dr. DeGroot.\
Because first_arr only gives $10$ elements, you can't reshape it into a $5$ by $3$ array. $5$ by $2$ though, that's pleanty doable!

In [10]:
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)

print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [12]:
s = "wooster physics"
print(s[0:4])

woos


2. For the string s above, print out the last 4 characters

In [14]:
print(s[-4:])

sics


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [15]:
my_list = [1.1, 1.2, 1.3, 1.4, 1.5]
print(my_list)

my_list[2] = -10.0
print(my_list)

[1.1, 1.2, 1.3, 1.4, 1.5]
[1.1, 1.2, -10.0, 1.4, 1.5]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [16]:
my_array = np.arange(0, 101, 5)
print(my_array)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [21]:
meas_list = []
reps = 0

while reps < 10:
    new_element = float(input("Pick a number between 1 and 10:"))
    meas_list.append(new_element)
    reps += 1

print(meas_list)

meas_avg = sum(meas_list) / len(meas_list)
print("Average:", meas_avg)
meas_max = max(meas_list)
print("Maximum:", meas_max)
meas_min = min(meas_list)
print("Minimum:", meas_min)

velocity = (55*1609.344) / 3600 #Converted mph to meters per second
print(velocity)

print("Average distance: ", meas_avg*velocity, " m", sep="")
print("Maximum distance: ", meas_max*velocity, " m", sep="")
print("Minimum distance: ", meas_min*velocity, " m", sep="")

[1.0, 2.0, 3.0, 7.0, 4.0, 9.0, 8.0, 5.0, 4.0, 6.0]
Average: 4.9
Maximum: 9.0
Minimum: 1.0
24.5872
Average distance: 120.47728000000001 m
Maximum distance: 221.2848 m
Minimum distance: 24.5872 m


### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [ ]:
heights = np.arange(0, 50.1, 0.5, float)
mass = 25 #kg
reps = 1
vel = 0 # initial velocity at zero

kinetic = np.zeros(101, float)
potential = np.zeros(101, float)

while reps < 102:
    vel += (1/2) * (9.8) #velocity changes every 1/2 meter

    new_kinetic = (0.5) * mass * vel**2
    kinetic[-reps] = round(new_kinetic, 1)
    
    new_potential = mass * (9.81) * heights[-reps]
    potential[-reps] = round(new_potential, 1)

    reps += 1

print(heights)
print(kinetic)
print(potential)


# I ran out of time here

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]
[3.0615751e+06 3.0012500e+06 2.9415251e+06 2.8824005e+06 2.8238761e+06
 2.7659520e+06 2.7086281e+06 2.6519045e+06 2.5957811e+06 2.5402580e+06
 2.4853351e+06 2.4310125e+06 2.3772901e+06 2.3241680e+06 2.2716461e+06
 2.2197245e+06 2.1684031e+06 2.1176820e+06 2.0675611e+06 2.0180405e+06
 1.9691201e+06 1.9208000e+06 1.8730801e+06 1.8259605e+06 1.7794411e+06
 1.7335220e+06 1.6882031e+06 1.6434845e+06 1.5993661e+06 1.5558480e+06
 1.5129301e+06 1.4706125e+06 1.4288951e+06 1.3877780e+06 1.3

I ran out of time while working on 'Write a script 2'. I don't think my 'vel' velocity updater is correct, but I can still see the general gist of 'less kinetic energy and more potential energy when the ball is forst dropped and vice-versa for when it's closer to the ground.'

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [34]:
# Ran out of time Monday :(