#### Name: 

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [1]:
import numpy as np
import math

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [3]:
#1 - define & index specific elements of a list
values = [2,3,4]
print(values[0])
print(values[2])

2
4


In [ ]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

In [11]:
#3 - define array annd change certain values 
arr1D = np.zeros(2, dtype=int)
arr1D[0] = 55
arr1D[1] = -999
print(arr1D)

[  55 -999]


In [13]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [14]:
s = 'wooster physics'
print(s)

wooster physics


2. For the string s above, print out the last 4 characters

In [16]:
print(s[-4:])

sics


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [17]:
Tony_list = [1.1,2.2,3.3,4.4,5.5]
print(Tony_list)
Tony_list[2] = 6.6
print(Tony_list)

[1.1, 2.2, 3.3, 4.4, 5.5]
[1.1, 2.2, 6.6, 4.4, 5.5]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [18]:
t = np.arange(0,100,5)
print(t)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [13]:
meas_list = []
for i in range(10):
    val = float(input(f"Enter measurement {i+1} (between 1-10): "))
    meas_list.append(val)
print(len(meas_list))
print(sum(meas_list) / len(meas_list))
print(max(meas_list))
print(min(meas_list))
velocity = 55
distances = [t * velocity for t in meas_list]
print(distances)


Enter measurement 1 (between 1-10): 4
Enter measurement 2 (between 1-10): 6
Enter measurement 3 (between 1-10): 2
Enter measurement 4 (between 1-10): 8
Enter measurement 5 (between 1-10): 4
Enter measurement 6 (between 1-10): 6
Enter measurement 7 (between 1-10): 4
Enter measurement 8 (between 1-10): 6
Enter measurement 9 (between 1-10): 4
Enter measurement 10 (between 1-10): 6
10
5.0
8.0
2.0
[220.0, 330.0, 110.0, 440.0, 220.0, 330.0, 220.0, 330.0, 220.0, 330.0]


### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.