#### Name: 

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [2]:
import math as m
import numpy as np


## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [7]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (172649615.py, line 3)

The code above has 3 main errors. Firstly, the code needs parentheses for each of the print operation. Secondly, the indexing makes me believe that the user wanted to call the 1st and 2nd elements of our list, but didn't start counting at 0. Lastly, they calling of specific indices is done with [] not ().

In [8]:
#1 Solution
values = (2,3,4)
print (values[1])
print (values[2])

3
4


In [ ]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

Assumably the code above wanted to concatenate the two lists, and for this operation we use '+' not '*'.

In [10]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [ ]:
#3 - define array and change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

The code above ist trying to redefine a value in 'Arr1d' which is not the same letter casing as 'arr1D'. Additionally the second variable redefining is outside our array (as [3,3] is not contained in the bounds of [0,0] to [1,1])

In [73]:
#3 - define array and change certain values 
arr1D = np.zeros([2,2], int)
arr1D[0,0] = 55
arr1D[1,1] = -999
print(arr1D)

[[  55    0]
 [   0 -999]]


In [ ]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

The code above tries to map an array of size 10 (given by (20-2)/2 + 1) to a size 15 (5*3). We either need to increase the size of our original array to 15, or decrease the size of the array we are mapping to to be 10. As the problem says reshape a 1D into a 2D, I am assuming we are not to change the original array, so we only need to change the column count from 3 to 2.

In [18]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [ ]:
s = "wooster physics"
s_list = list(s) #Converting out string into a list ie [w,o,o,s,t,e,r, ,p,h,y,s,i,c,s]
Print = "" #Defining out variable that will later be printed
for i in range(0,4): #Concatenating the first 4 letters with a for loop
    Print = Print + s_list[i]
print(Print)

woos


2. For the string s above, print out the last 4 characters

In [ ]:
Print = "" #Defining out variable that will later be printed
for i in range(0,4): #Concatenating the last 4 letters with a for loop
    Print = Print + s_list[len(s_list)-4+i]
print(Print)

sics


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [ ]:
Positive_List = [0.1,0.2,0.3,0.4,0.5] #List of 5 different positive float values
print(Positive_List)
Positive_List[2] = -10.0 #Redefining the 3rd value (we index at 0, so 3rd=2)
print(Positive_List)

[0.1, 0.2, 0.3, 0.4, 0.5]
[0.1, 0.2, -10.0, 0.4, 0.5]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [70]:
t = np.arange(0,105,5)
print(t)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [ ]:
meas_list = [] #Defining list
dist_list = [] #Defining list
Vel = 55 #Defining velocity
Conversion = 0.44704 #For converting mph to m/s
for i in range(0,10): #For loop, appending user input to meas_list for 10 inputs and bounding between 1 and 10
    User_Input = float(input("Please choose a number between 1 & 10: "))
    while User_Input < 1 or User_Input > 10:
        User_Input = float(input("Between 1 & 10: "))
    meas_list.append(User_Input)
print(len(meas_list)) #Checking errors
Ave_List = sum(meas_list)/len(meas_list) 
print(Ave_List)#Printing average
Max_list = max(meas_list)
print(Max_list) #Printing maximum
Min_list = min(meas_list)
print(Min_list) #Printing minimum
for i in range(0,10): #For loop defining dist_list as 55 times each index of meas_list
    dist_list.append(Vel*meas_list[i]*Conversion)
print(dist_list) #Printing dist_list

First I define meas_list & dist_list as empty lists, our velocity constant of 55 mph, and our conversion ratio from mph to m/s. I then generate meas_list based off of user input, using a for loop to repeat the iterative process 10 times, and an while loop to prevent the user from inputting values outside our bounds of 1-10. I define and print values as expected. I additionally use a for loop for defining our distance list, before printing said list.

### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [ ]:
height_array = np.arange(0,50.5,0.5)
print(height_array)
mass = float(input("Mass of the object: "))
gravity = float(9.81)
Energy_max = mass*gravity*height_array[len(height_array)-1]
print(Energy_max)

#Defining Potential Energy Array using U = m*g*h
potential_array = mass*gravity*height_array
print(potential_array)
#Defining Kinetic Energy Array using T = E_max - U
kinetic_array = Energy_max - potential_array
print(kinetic_array)


Firstly I define the height array using np.arrange as we have a bounded array with set intervals, before printing the height array. I then ask the user for an input mass, before defining gravity. I then define a maximum energy given by m.g.h_max which I then print. I then define potential and kinetic energy array before printing them.

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [72]:
spinosaurus = np.array(([[1,2,3,4,5],[3,4,5,6,7],[8,9,10,11,12],[13,14,15,16,17],[18,19,20,21,22]]))
print(spinosaurus)
middle_row = spinosaurus[2,:]
print(middle_row)
third_column = spinosaurus[:,2]
print(third_column)
mini_spinosaur = np.array([[5,6],[10,11]])
mini_spinosaur = mini_spinosaur**2
print(mini_spinosaur)

[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]
[ 8  9 10 11 12]
[ 3  5 10 15 20]
[[ 25  36]
 [100 121]]


I first use a list inside np.array to define spinosaurus as a np.array using one line before printing spinosaurus. I then use the indexing functionality of numpy to print the middle row and third column. I then define mini_spinosaur like I did for spinosaur, before squaring mini_spinosaur and printing the outcome.