#### Name: Noah Hankin

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [106]:
import math
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [ ]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

This code won't work for a few reasons. values is supposed to be a list, but Python won't think it's a list because the wrong brackets are used. They should be square brackets, not parenthesis.
Also, the second line won't display a number, as the parenthesis should be square brackets. If the intention is to print the '3' in values, the number inside the argument should be 1. 
The last line won't print anything, as the third index in "values" doesn't exist. Python starts indices at 0 and not 1, so to display the last index of the list, the '3' in the square brackets should be a '2'.
Finally, both print statements need parenthesis around them.

In [2]:
#1 Corrected
values = [2,3,4]
print(values[1])
print(values[2])

3
4


In [ ]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

The intention of this code is the concatenate the two lists "first_names_a" and "first_names_b" to make one list first_names. However, using "*" won't concatenate the lists. The correct symbol is "+."

In [3]:
#2 Corrected 
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [ ]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

There's two issues with this. The second line is wrong, as "Arr1d" is different than "arr1D," so the array "Arr1d" doesn't exist. This is because Python is case sensitive. The third line is also wrong. It asks to change the element in the 4th row and 4th column from 0 to -999m but "arr1D" only has 2 rows and columns. Also, it would help to print arr1D at the end of this code to see if the changes we tried implementing worked.

In [16]:
#3 Corrected
arr1D = np.zeros([2,2], int)
arr1D[0,0] = 55 #Changed to 0,0 as this was likely what the original programmer intended
arr1D[1,1] = -999 #Changed to 1,1 as this was likely what the original programmer intended
print(arr1D)

[[  55    0]
 [   0 -999]]


In [ ]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

This code is nearly correct. The only issue is that "first_arr" has 10 elements, and "second_arr" wants to reshape it into an array with 15 entries (5x3 array). Since the number of elements don't match, this code won't work.

In [17]:
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2) # Changed the 3 to a 2 to make this work
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [18]:
s = "wooster physics"
print(s[0:4])

woos


2. For the string s above, print out the last 4 characters

In [21]:
print(s[len(s)-4:])

sics


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [23]:
floats = [9.1, 4.6, 8.2, 0.3, 7.5]
print(floats)
floats[2] = -10.0
print(floats)

[9.1, 4.6, 8.2, 0.3, 7.5]
[9.1, 4.6, -10.0, 0.3, 7.5]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [24]:
t = np.arange(0, 101, 5)
print(t)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [117]:
meas_list = []
n = 0  # make a counter for while loop
x = 0
while n<10: # make sure use less than and not greater than...
    new_num = float(input("Please enter a number between 1 and 10: "))
    if new_num < float(1) or new_num > float(10):
        print("This is not between 1 and 10. :/")
        break
    else:
        meas_list.append(new_num)
        n = n + 1
        if n == 10:  # adds way to break out of loop
            x = 1
            break
if(x==1):
    print(meas_list)
    #print(len(meas_list))

Please enter a number between 1 and 10:  9
Please enter a number between 1 and 10:  9
Please enter a number between 1 and 10:  9
Please enter a number between 1 and 10:  9
Please enter a number between 1 and 10:  9
Please enter a number between 1 and 10:  7
Please enter a number between 1 and 10:  8
Please enter a number between 1 and 10:  6
Please enter a number between 1 and 10:  5
Please enter a number between 1 and 10:  1


[9.0, 9.0, 9.0, 9.0, 9.0, 7.0, 8.0, 6.0, 5.0, 1.0]


I figured that using a while loop would work well to ask the user for an input 10 times. I included a counter "n" that goes from 0 to 9, and the while loop breaks when n = 10 (after 10 entries). I also added a couple lines that stop the code from running if a number not between 1 and 10 is entered. I don't have the time to figure out how to make Python "forget" this number and allow the user to re-enter an approriate number, but I think this would be fun to add.

### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [72]:
#Define constants
m = 10.0 # mass of object in kg
g = 9.81 #accel due to gravity on Earth (m/s^2)

#Define height array
heights = np.arange(0, 50.5, 0.5) # heights in m
print(heights)


#Start with potential --> mgh
pot_energy = m*g*heights #definition of gravitational potential energy
print(pot_energy)

#Now, do kinetic --> 1/2*m*v^2
#So, we need to get v for every height --> use v^2 = v0^2 + 2*a*height

vel = -np.sqrt(2*g*(50-heights)) # these are velocities at every height - include negative for direction
#print(vel) 

kin_energy = 0.5*m*vel**2
print(kin_energy)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]
[   0.     49.05   98.1   147.15  196.2   245.25  294.3   343.35  392.4
  441.45  490.5   539.55  588.6   637.65  686.7   735.75  784.8   833.85
  882.9   931.95  981.   1030.05 1079.1  1128.15 1177.2  1226.25 1275.3
 1324.35 1373.4  1422.45 1471.5  1520.55 1569.6  1618.65 1667.7  1716.75
 1765.8  1814.85 1863.9  1912.95 1962.   2011.05 2060.1  2109.15 2158.2
 2207.25 2256.3  2305.35 2354.4  2403.45 2452.5  2501.55 2550.6  2599.65
 2648.7  2697.75 2746.8  2795.85 2844.9  2893.95 29

The arrays look how I'd expect. As the heights increase, the potential energies increase linearly. Conversely, as the heights and PE increase, the kinetic energy decreases. Also, the values make sense, as the KE at height = 50 m is the same as the PE at height = 0 m. Energy is being conserved as expected.

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [108]:
# a)

row1 = list(range(1, 6, 1))
others = list(range(3, 23, 1))
spino_list = row1 + others #concatenate two lists before making into an array
#print(spino_list)
spinosaurus = np.array(spino_list).reshape(5, 5) #transform the list into a 5x5 array
#print(spinosaurus)

# b)
print(spinosaurus[2,:]) #prints third row. putting a colon in the column input means the whole row is printed

# c)
print(spinosaurus[:,2]) #prints third column. putting a colon in the row input means the whole column is printed

# d)
minispinosaur = spinosaurus[1:3, 2:4] #creates a submatrix from rows 1 to 2 and columns 2 to 3 (remember that the second number is non-inclusive)
#print(minispinosaur)

#e) 
minispin_square = minispinosaur**2
print(minispin_square)

[ 8  9 10 11 12]
[ 3  5 10 15 20]
[[ 25  36]
 [100 121]]


To make spinosaurus array, I concatenated two lists and transformed the combined list into an array. The first list is the first row and the second list is the rest of the array. I did it this way because the array, excluding the first row, counts up by 1 from 3 to 22, while the first row counts up by 1 from 1 to 5. 
For part b), I used a colon in place of the column to ensure the whole row was displayed. I did the same for c), but in place of the row to ensure the whole column printed and not just a subset of the column. 
For part d), I sliced out a submatrix. When I initially coded this, I forgot that the bth element in "a:b" for counting is not included. 
For part e), I simply needed to square the submatrix because arithmetic operations apply to all elements of an array. 