#### Name: Jon Stowers

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [6]:
import math
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [ ]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

First, the list and the index are formatted using parentheses instead of square brackets.
Second, the indexes forget that the list starts counting at 0, so the second value in the list is index [1] and the third value is index [2].
Finally, the print statements were missing the necessary parentheses.

In [3]:
#1 - define & index specific elements of a list
values = [2,3,4]
print( values[1])
print( values[2])

3
4


In [ ]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

The only mistake with this code is that it attempts to concatenate the lists with a *, when it needs a + instead.

In [4]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [ ]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

The variable name is typed incorrectly, so the code doesn't recognize Arr1d because it should be arr1D.
The index [3,3] is not within the array because it is only 2x2, so I changed it to an index in the array.

In [9]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
arr1D[1,1] = 55
arr1D[0,0] = -999
print(arr1D)

[[-999    0]
 [   0   55]]


In [ ]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

The mistake with this code is that it tries to reshape first_arr (which has 10 entries) into a 5x3 array. That is too large; it needs to be 5x2.

In [13]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [15]:
s = 'wooster physics'
print(s[0:4])

woos


2. For the string s above, print out the last 4 characters

In [ ]:
print(s[len(s)-4:len(s)]) #calculates based on length of string instead of simply counting characters and using specific numbers in the code

sics


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [17]:
list1 = [2.0,4.0,6.0,8.0,10.0]
print(list1)
list1[2] = -10.0
print(list1)

[2.0, 4.0, 6.0, 8.0, 10.0]
[2.0, 4.0, -10.0, 8.0, 10.0]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [18]:
t = np.arange(0,101,5) #goes to 101 so that 100 is included
print(t)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [ ]:
meas_list = [] #assuming time in hours

for _ in range(10):
    meas_list.append(float(input('Enter a number between 1 and 10.'))) #needs to be a float or an int because the default of input() yields a str

print('The length of the list is',len(meas_list))

avg = sum(meas_list)/len(meas_list)
maximum = max(meas_list)
minimum = min(meas_list)

print('The average time is',avg,'hours.')
print('The maximum time is',maximum,'hours.')
print('The minimum time is',minimum,'hours.')

v_obj = 55 #miles per hour
v_obj_m = v_obj*1610 #m per hour (approximately)


avg *= v_obj_m
maximum *= v_obj_m
minimum *= v_obj_m


print('The average distance is',avg,'meters.')
print('The maximum distance is',maximum,'meters.')
print('The minimum distance is',minimum,'meters.')




The length of the list is 10
The average time is 3.0 hours.
The maximum time is 5.0 hours.
The minimum time is 1.0 hours.
The average distance is 265650.0 meters.
The maximum distance is 442750.0 meters.
The minimum distance is 88550.0 meters.


To ask the user for the times, I used a for loop that runs 10 times and the append() command to add to the empty list.

To calculate the average, I used the sum of the list divided by the length of the list, and I used the built-in max and min commands to produce the maximum and minimum values from the list.

Then, I used the approximation that 1 mi is 1.61 km to convert the speed in miles per hour to meters per hour. 
Finally, I simply multiplied the average, max, and min values by the speed to yield the distance travelled in those times.

### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [ ]:

heights = np.arange(0,50.1,0.5,float) #stops at 50.1 to include 50
print(heights) #in meters
print()

m = 5 #object mass in kg


pe = np.copy(heights) #potential energy in J
pe = pe*m*9.81 #multiplies each entry by the mass and 9.81 m/s2 via the formula U = mgh
print(pe)
print()

Etot = max(pe) #maximum potential energy is the same as mechanical energy, and will be the maximum kinetic energy as well


ke = (pe*-1)+Etot #kinetic energy in J


print(ke)




[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]

[   0.      24.525   49.05    73.575   98.1    122.625  147.15   171.675
  196.2    220.725  245.25   269.775  294.3    318.825  343.35   367.875
  392.4    416.925  441.45   465.975  490.5    515.025  539.55   564.075
  588.6    613.125  637.65   662.175  686.7    711.225  735.75   760.275
  784.8    809.325  833.85   858.375  882.9    907.425  931.95   956.475
  981.    1005.525 1030.05  1054.575 1079.1   1103.625 1128.15  1152.675
 1177.2   1201.725 1226.25  1250.775 1275.3   1

First, I used the np.arange() command to produce increasing heights from 0 to 50 m. I then defined an arbitrary object mass of 5 kg.

Then, I used the formula of U = mgh to produce an array of potential energies. As expected, the potential energy at [0] is zero, and the potential energy at the maximum height is the maximum PE. 

Since the object is at rest at the maximum height, the maximum PE is the total mechanical energy E of the object. So, I know that max(pe) is also max(ke), where the maximum kinetic energy is at height 0. So to translate from pe to ke, I used the formula of E - U = K. As expected, the kinetic energy at the maximum height is 0, and the kinetic energy at [0] is equal to the maximum potential energy.

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

In [ ]:
#a)
spinolist1 = list(range(1,6)) #will become the top row of the array
spinolist2 = list(range(3,23)) #will become the other rows of the array
spinolist = spinolist1+spinolist2 #This is the easiest way I could think of to produce the correct values
#print(spinolist) #used as a test

spinosaurus = np.array(spinolist) #changes list into array
spinosaurus = spinosaurus.reshape(5,5) #redimensions array into stipulated form
print(spinosaurus) 
print()

#b)
print(spinosaurus[2,:]) #middle row, all columns
print()

#c)
print(spinosaurus[:,2]) #all rows, column number 2 is third column
print()

#d)
mini_spinosaur = spinosaurus[1:3,2:4]
print(mini_spinosaur)
print()

#e)
print(mini_spinosaur**2)


[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]

[ 8  9 10 11 12]

[ 3  5 10 15 20]

[[ 5  6]
 [10 11]]

[[ 25  36]
 [100 121]]


To set up the array, since row the first row doesn't quite follow the same incramental pattern as the second-fifth rows, I created two lists that would "feed" into the spinosaurus array, called spinolist1 and spinolist2, which would then be combined into one list. I could then turn spinolist into an array and reshape it into a 5x5 array with the entries in the right places.

Then, selecting the middle row and the third column just took use of indexing, and creating the mini_spinosaur array also used careful indexing. FInally, squaring all the entries in mini_spinosaur was as simple as squaring the array.
