#### Name: Mason Miller

# PHYS 230 Lab Assignment 2

### Monday, January 26, 2026: Chapter 2.4
- Lists 
- Arrays (Numpy)

#### Start by importing any packages you need below (feel free to update as you go):

In [11]:
import math as m
import numpy as np

## Catch the errors! (20 pts - 5 pts each)

For each of the following cells, find the error (or errors), and correct it (or them) by:<br> 
    a. add a new markdown cell that describes what was wrong with the code,<br>
    b. creating a new code cell with the corrected code (where possible)<br>
<br>
**Make sure to write in complete sentences; corrected code with a poorly written explanation will not receive better than 4 of 5 points on a given question.** I am not looking for a lengthy explanation; but one that is sufficiently detailed to explain the errors. 

In [1]:
#1 - define & index specific elements of a list
values = (2,3,4)
print values(2)
print values[3]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (172649615.py, line 3)

There must be parenthesis around the values(2) (which should be values[2]) and values[3]. Values[3] is also outside of the range, only 0, 1 and 2 can be indexed.

In [5]:
#1 (corrected)- define & index specific elements of a list
values = (2,3,4)
print(values[0])
print(values[1])
print(values[2])

2
3
4


In [9]:
#2 - create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a * first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


To combine the lists, + should be used instead of *.

In [7]:
#2 (corrected)- create a single list of all the first names in each individual list  
first_names_a = ['Eliza', 'Evan', 'Mark', 'Kallee']
first_names_b = ['DJ', 'Zander', 'Sean', 'Josh', 'Matt']
first_names = first_names_a + first_names_b
print(first_names)

['Eliza', 'Evan', 'Mark', 'Kallee', 'DJ', 'Zander', 'Sean', 'Josh', 'Matt']


In [ ]:
#3 - define array annd change certain values 
arr1D = np.zeros([2,2], int)
Arr1d[1,1] = 55
arr1D[3,3] = -999

Capitilization has to be consistent! Arr1d -> arr1D. The line: arr1D[3,3] = -999 will not work; 3,3 is outside of the range of the original array. We can change it to arr1D[0,1] = -999. I will also add print statements to see whats going on.

In [18]:
#3 (corrected)- define array and change certain values 
arr1D = np.zeros([2,2], int)
print(arr1D)
arr1D[1,1] = 55
print(arr1D)
arr1D[0,1] = -999
print(arr1D)

[[0 0]
 [0 0]]
[[ 0  0]
 [ 0 55]]
[[   0 -999]
 [   0   55]]


In [ ]:
#4 - reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,3)
print(first_arr)
print(second_arr)

first_arr will have 10 values, but [5,3] has 15 values. If we change that to [5,2], then the reshaped array will match the number of values.

In [22]:
#4 (corrected)- reshape a 1D array into a 2D array 
first_arr = np.arange(0,20,2)
second_arr = first_arr.reshape(5,2)
print(first_arr)
print(second_arr)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


## Short python snippets (20 pts - 5 pts each)
Below each markdow cell, write a short python snippet to perform the indicated action; you might have to use google to find out how to perform some of these actions--this is deliberate on my part. Google and *stack overflow* are your friends.<br>
Add a markdown cell to explain your thinking if this is needed.

1. Define a string variable s; assign the value 'wooster physics' to it, and then print out first 4 characters

In [26]:
s = 'wooster physics'
print(s[:4])

woos


2. For the string s above, print out the last 4 characters

In [32]:
print(s[11:])

sics


3. Define a list with 5 different positive float values & print it. Then replace the 3rd value with -10.0, and print the list again. 

In [35]:
five = [1, 3, 5, 7, 9]
print(five)
five[2] = -10
print(five)

[1, 3, 5, 7, 9]
[1, 3, -10, 7, 9]


4. Create a numpy array called $t$ that includes points between 0 and 100 counting by 5's.  Print out the array.

In [37]:
t = np.arange(0, 100, 5)
print(t)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


### Write a script 1 (25 pts) - Lists 

Let's build and analyze a list of measurements:
- Create an empty list called "meas_list"
- Ask the user 10 times for a number between 1 and 10 & append to the list 
    - Print the length of the list to make sure it is correct! 
- Calculate the average, maximum, and minimum of the list & print these values
- Assuming all of these are values of time, convert the values into distance (in meters) by multiplying by the constant velocity the object is traveling (55 mph) & print your results

When your program is complete, add a markdown cell below it to explain your process and program. 

In [53]:
meas_list = []

#prompt and append numbers to the list
while len(meas_list) <= 9:
    list_val = float(input("Input a number between 1 and 10"))
    meas_list.append(list_val)
#print the length of the list and the list itself
print(len(meas_list))
print(meas_list)

#find and print average
avg = sum(meas_list) / len(meas_list)
print("Average:",avg)

#find and print maximum
maximum = max(meas_list)
print("Maximum:", maximum)

#find and print maximum
minimum = min(meas_list)
print("Minimum:", minimum)

#convert the list to an array, multiply by a scalar, print the array
dist_array = np.array(meas_list)
dist_array = dist_array * 55
print("Distances traveled:", dist_array)

Input a number between 1 and 10 1
Input a number between 1 and 10 2
Input a number between 1 and 10 3
Input a number between 1 and 10 4
Input a number between 1 and 10 5
Input a number between 1 and 10 6
Input a number between 1 and 10 7
Input a number between 1 and 10 8
Input a number between 1 and 10 9
Input a number between 1 and 10 9


10
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 9.0]
Average: 5.4
Maximum: 9.0
Minimum: 1.0
Distances traveled: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 45.]


My program uses a while loop to prompt the user for 10 integers between 1 and ten. It requires numerical inputs due to the float command. After each user input, that value is appended to the meas_list. The average, maximum, and minimum values are found and printed. I converted the list to an array so that I could multiply it by the velocity, and printed the array.



### Write a script 2 (25 pts) - Arrays 
#### Calculate kinetic and potential energy without air resistance 

Use numpy arrays to complete the following:
- Create a 1D array of heights ranging from 0 to 50 m counting by 0.5 m
- Define the mass of the object 
- If the object is at rest at 50 m, calculate two arrays of the kinetic and potential energy of the object at each height. Ignore air resistance. 
- print the height array, kinetic energy array, and potential energy array 
    - do the arrays look like you would expect?

In [61]:
heights = np.arange(0, 50.5, 0.5)

mass = float(input('Mass?'))
g = 9.8
total_energy = mass * g * 50
pe_array = mass * g * heights
ke_array = total_energy - pe_array
print(heights)
print(pe_array)
print(ke_array)


Mass? 5


[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]
[   0.    24.5   49.    73.5   98.   122.5  147.   171.5  196.   220.5
  245.   269.5  294.   318.5  343.   367.5  392.   416.5  441.   465.5
  490.   514.5  539.   563.5  588.   612.5  637.   661.5  686.   710.5
  735.   759.5  784.   808.5  833.   857.5  882.   906.5  931.   955.5
  980.  1004.5 1029.  1053.5 1078.  1102.5 1127.  1151.5 1176.  1200.5
 1225.  1249.5 1274.  1298.5 1323.  1347.5 1372.  1396.5 1421.  1445.5
 1470.  1494.5 1519.  1543.5 1568.  1592.5 1617.  1641.5 166

The arrays didnt look like what I expected at first; I expected the kinetic energy array to increase and the potential energy to decrease. I realize now that the heights are counting up, so everything makes sense.

### Write a script 3 (25 pts) - Arrays: indexing & Slicing 

**(a)** Define a 2d numPy array called `spinosaurus` that looks like this:
$$
 \begin{bmatrix}
    1  & 2  & 3  & 4  & 5 \\
    3  & 4  & 5  & 6  & 7 \\
    8  & 9  & 10 & 11 & 12\\
    13 & 14 & 15 & 16 & 17\\
    18 & 19 & 20 & 21 & 22
  \end{bmatrix}
$$

**(b)** Print out the middle row.

**(c)** Print out the third column.

**(d)** Define and print out a new array called `mini_spinosaur` which includes this subset of the array:
$$
 \begin{bmatrix}
     5  & 6  \\
    10 & 11 
  \end{bmatrix}
$$
**(e)** Square every element of the `mini_spinosaur` and print the result.

It is 3:53 and I am out of time. I would create the array with numpy.arrange. I could do part d by creating arrays out of the original one. 