# Class 12: Solving Linear Equations 

Ch. 6, section 1: Gaussian Elimination, Backsubstitution, Pivoting, & LU Decomposition    

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [1]:
import numpy as np

### Gaussian Elimination with backsubstitution 

Let's solve the example from the book: Use Gaussian Elimination to find $w, x, y,$ and $z$. 

$$\begin{pmatrix}
2 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [15]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [14]:
# gaussian elimination with backsubtitution 

for m in range(N):
    # divide by diagonal elements
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div
    
    # subtract from lower rows
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# apply backsubstitution
for m in range(N-1,-1,-1): # start at the end, move at one step to zero
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)

[ 2. -1. -2.  1.]


In [11]:
print(x)

[nan nan nan nan]


**note** this works for matrices of any size 

### Pivoting 

We need to interchange rows of the matrix for certain situations. Let's see an example below. 

$$\begin{pmatrix}
0 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [22]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


What happens when we run Gaussian Elimination on this system of equations? 

In [17]:
for m in range(N):
    # divide by diagonal elements
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div
    
    # subtract from lower rows
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# apply backsubstitution
for m in range(N-1,-1,-1): # start at the end, move at one step to zero
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)

[nan nan nan nan]


C:\Users\ktown\AppData\Local\Temp\ipykernel_46296\4191558132.py:4: RuntimeWarning: divide by zero encountered in divide
  A[m,:] /= div
C:\Users\ktown\AppData\Local\Temp\ipykernel_46296\4191558132.py:4: RuntimeWarning: invalid value encountered in divide
  A[m,:] /= div
C:\Users\ktown\AppData\Local\Temp\ipykernel_46296\4191558132.py:5: RuntimeWarning: divide by zero encountered in scalar divide
  v[m] /= div
C:\Users\ktown\AppData\Local\Temp\ipykernel_46296\4191558132.py:5: RuntimeWarning: invalid value encountered in scalar divide
  v[m] /= div


In [ ]:
# pivoting
for m in range(N):
    # find the row with the larggest pivot element is
    pivot = m
    largest = np.abs(A[m,m])
    for i in range(m+1,N):
        if np.abs(A[i,m]) > largest:
            largest = np.abs(A[i,m])
            pivot = i

    # swap rows
    for j in range(N):
        A[m,j], A[pivot,j] = A[pivot,j], A[m,j]

    # gaussian elimination with backsubtitution 

    for k in range(N):
        # divide by diagonal elements
        div = A[k,k]
        A[k,:] /= div
        v[k] /= div
        
        # subtract from lower rows
        for i in range(k+1,N):
            mult = A[i,k]
            A[i,:] -= mult*A[k,:]
            v[i] -= mult*v[k]

# apply backsubstitution
for m in range(N-1,-1,-1): # start at the end, move at one step to zero
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(A)
print(x)

[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.          1.          4.          1.        ]
 [ 0.          0.          1.          0.47058824]
 [ 0.          0.          0.          1.        ]]
[ 1.28571429 -1.67857143  1.17857143 -0.03571429]


### LU Substitution 

Apply LU substitution to the same matrices 

In [ ]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)

# solving with numpy
x = np.linalg.solve(A,v)

print(A)
print(x)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[ 2. -1. -2.  1.]
[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


In [30]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# solving with numpy
x = np.linalg.solve(A,v)

print(A)
print(x)

# calculatin inverse
from numpy.linalg import inv
X = inv(A)
print(X)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[ 1.61904762 -0.42857143 -1.23809524  1.38095238]
[[-0.0952381  -0.04761905 -0.47619048  0.80952381]
 [ 0.14285714  0.32142857  0.46428571 -0.71428571]
 [ 0.19047619 -0.1547619  -0.29761905  0.38095238]
 [ 0.0952381   0.29761905  0.72619048 -0.80952381]]


**note** if want to perform LU decomposition separately from backsubtitution, can do so. Check out www.scipy.org to learn how to do so

In paricular, the Decompositions section of https://docs.scipy.org/doc/scipy/reference/linalg.html