# Class 03: Basics of Python Programming 2

## Lists & Arrays 

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [14]:
import math as m
import numpy as np

### Let's talk through a couple if/while statements first! 

In [ ]:
# if, else, and elif statements 
import random 

n = int(input("Choose a number between 1 and 100: "))
if n>100:
    print("you have chosen a number outside of the boundaries. Assigning number now.")
    n = random.randint(1, 101)
    print("your number is: ", n)
elif n < 1:
    print("you have chosen a number outside of the boundaries. Assigning number now.")
    n = random.randint(1, 101)
    print("your number is: ", n)
else: 
    print("your number is: ", n)

In [ ]:
x = -105

while x<0:
    print("x is less than 0")
    x = x+1
    print(x)
    if x == -100:
        break    
        
print("x is now ", x)

##  Lists in Python

- Let's make a list - define 4 variables and make a list out of them 

In [2]:
a = 3
b = 15.4
c = "cat"
d = 1 +2j
my_list = [a,b,c,d]
print(my_list)
print(type(my_list))

[3, 15.4, 'cat', (1+2j)]
<class 'list'>


 - now change the value of a in the cell below and then print the list again. What happens to the list? 

In [3]:
a = -22
print(my_list)
my_list[0] = -56.2
print(my_list)

[3, 15.4, 'cat', (1+2j)]
[-56.2, 15.4, 'cat', (1+2j)]


####  Indexing

-  reference certain components of a vector list to calculate magnitude:
    - Define the list r, containing information about the x, y, and z position of an object 
    - Calculate the magnitude of a vector pointing from the origin to point r

In [4]:
r = [2,5,8]

magnitude = m.sqrt(r[0]**2 + r[1]**2 + r[2]**2)
print(magnitude)

9.643650760992955


#### Operations on lists  

-  Define two lists, a and b, each consisting of 3 integers 
    - Add the two lists together, call it c, and print out
    - Now multipy c by 2
    - Print out the length of c
    - Append one additional number to the list c

In [10]:
list_a = [3, 4, 5]
list_b = [10, 11, 12]
list_c = list_a + list_b
print(list_c)
list_c *= 2
print(list_c)
print(len(list_c))
list_c.append(13)
print(list_c)

[3, 4, 5, 10, 11, 12]
[3, 4, 5, 10, 11, 12, 3, 4, 5, 10, 11, 12]
12
[3, 4, 5, 10, 11, 12, 3, 4, 5, 10, 11, 12, 13]


####  Applying built-in mathematical operations to a list

- Find the average of the list abc below using any combination of the following built-in functions for lists: 
    sum(), max(), min(), len() 
- Print out the result 


- Create a new list that consists of the following: 
    - the first element of abc multipled by 2
    - the second element of abc multiplied by the third element
    - the third element of abc cubed and divided by the second element. 
- Print out your new list

In [13]:
abc = [1.0, 1.5, 2.2]
average = sum(abc)/len(abc)
print(average)

new_abc = [abc[0]*2,round(abc[1]*abc[2]),round((abc[2]**3)/abc[1])]
print(new_abc)

1.5666666666666667
[2.0, 3, 7]


## Arrays with Numpy


In [16]:
xarray = np.arange(0,16,5,float)
print(xarray)

[ 0.  5. 10. 15.]


#### Creating arrays 

- Use Numpy to create an 2D array (5 rows, 2 columns) of zeros that are floats

In [17]:
new_array = np.zeros([5,2], float)
print(new_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


- Now create a 5 row, 2 column array using np.empty
    - What do you notice? 

In [18]:
empty_arry = np.empty([5,2], int)
print(empty_arry)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


- take the list below and convert it to an array 
- check the type of both the list and the array 

In [21]:
alist = [1,2,3,4,5]
print(alist)
print(type(alist))
a_array = np.array(alist)
print(a_array)
print(type(a_array))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


- Create an array abc and see what these do:

In [23]:
abc = a_array

In [24]:
print(abc.ndim)
print(abc.shape)
print(abc.size)
print(abc.dtype)
print(abc.itemsize)
print(type(abc))
help(abc)

1
(5,)
5
int64
8
<class 'numpy.ndarray'>
Help on ndarray:

array([1, 2, 3, 4, 5])
    ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
    --

    ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)

    An array object represents a multidimensional, homogeneous array
    of fixed-size items.  An associated data-type object describes the
    format of each element in the array (its byte-order, how many bytes it
    occupies in memory, whether it is an integer, a floating point number,
    or something else, etc.)

    Arrays should be constructed using `array`, `zeros` or `empty` (refer
    to the See Also section below).  The parameters given here refer to
    a low-level method (`ndarray(...)`) for instantiating an array.

    For more information, refer to the `numpy` module and examine the
    methods and attributes of an array.

    Parameters
    ----------
    (for the __new__ method; see Notes below)

    shape : tuple of ints

- Print xarray from the class notes. How does arange work? 
    

In [25]:
xarray = np.arange(0,15,5, float)
print(xarray)

[ 0.  5. 10.]


- Create a 2D array (arr2d) with 15 numbers in it
- reshape it to a 2D array that is 3 rows by 5 columns 
- change the 0 to a 42 & 105 to 999

In [33]:
arr2d = np.arange(0,216,15).reshape(3,5)
print(arr2d)

arr2d[0,0] = 5
arr2d[2,3] = 67
print(arr2d)

[[  0  15  30  45  60]
 [ 75  90 105 120 135]
 [150 165 180 195 210]]
[[  5  15  30  45  60]
 [ 75  90 105 120 135]
 [150 165 180  67 210]]


#### Arithmetic with arrays 
Try the following:
- divide a arr2D by itself
- add arr2D to itself 

In [35]:
new_arr = arr2d / arr2d
print(new_arr)

new_guy = arr2d+arr2d
print(new_guy)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 10  30  60  90 120]
 [150 180 210 240 270]
 [300 330 360 134 420]]


#### Loading in data from text file 
- Download numbers.txt and numbers2D.txt from Moodle or the book website 
- print both out to see what they look like
- print the element from numbers2D that is in the third row and second column 

#### Mathematical functions on arrays 
- Define a new array that is the absolute value of the numbers2D array 
- Define a new array that is the square root of the numbers2D array

#### Copying arrays 
- Use np.copy to make a copy of the numbers2D array
- replace one of the elemnts in the copy array and print back out both arrays 

### <font color='purple'> Sets & Dictionaries </font> 

Here is an example set made from a list: 

To create an example dictionary, let's say that I have the following data:
- voltage = 2 V, 4 V, 6 V
- current = 1 A, 2 A, 3 A
- uncertainty in voltage = 0.05 V for all 

Below we will: 
- Make the dictionary based on these values and keys
- Add the key and elements: resistance = 2.0 ohms for all 
- list the keys & dictionary 
- print out the second element of one of the key arrays in the dictionary 