# Class 12: Solving Linear Equations 

Ch. 6, section 1: Gaussian Elimination, Backsubstitution, Pivoting, & LU Decomposition    

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [3]:
import numpy as np

### Gaussian Elimination with backsubstitution 

Let's solve the example from the book: Use Gaussian Elimination to find $w, x, y,$ and $z$. 

$$\begin{pmatrix}
2 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [4]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [10]:
# gaussian elimination with backsubtitution
for m in range(N):
    diag = A[m,m] #diagonal component of row A
    A[m,:] = A[m,:]/diag #divide each component in row by diagonal component
    v[m]= v[m]/diag #divide row m in v by same value

    for i in range(m+1,N):
        first = A[i,m] #first nonzero element of each lower row
        A[i,:] -= first*A[m,:] #subtract appropriate multiple of top row from lower rows
        v[i] -= first*v[m]

print(A)
print(v)

#backsubstitution
for m in range(N-1,-1,-1): #3,2,1,0 for above matrix
    x[m] = v[m] #x[3] = v[3]
    for i in range(m+1, N): 
        x[m] = x[m] - A[m,i]*x[i] #for example x = v1 - a12y - a13z

print(x)

[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]
[-2.   3.6 -2.   1. ]
[ 2. -1. -2.  1.]


**note** this works for matrices of any size 

### Pivoting 

We need to interchange rows of the matrix for certain situations. Let's see an example below. 

$$\begin{pmatrix}
0 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [30]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


What happens when we run Gaussian Elimination on this system of equations? 

In [31]:
# gaussian elimination with backsubtitution
for m in range(N):
    diag = A[m,m] #diagonal component of row A
    A[m,:] = A[m,:]/diag #divide each component in row by diagonal component
    v[m]= v[m]/diag #divide row m in v by same value

    for i in range(m+1,N):
        first = A[i,m] #first nonzero element of each lower row
        A[i,:] -= first*A[m,:] #subtract appropriate multiple of top row from lower rows
        v[i] -= first*v[m]

print(A)
print(v)

#backsubstitution
for m in range(N-1,-1,-1): #3,2,1,0 for above matrix
    x[m] = v[m] #x[3] = v[3]
    for i in range(m+1, N): 
        x[m] = x[m] - A[m,i]*x[i] #for example x = v1 - a12y - a13z

print(x)

[[nan inf inf inf]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
[-inf  nan  nan  nan]
[nan nan nan nan]


/var/folders/zm/rgyh3v1x1vg4dh61b936nxf40000gn/T/ipykernel_49088/3305441358.py:4: RuntimeWarning: divide by zero encountered in divide
  A[m,:] = A[m,:]/diag #divide each component in row by diagonal component
/var/folders/zm/rgyh3v1x1vg4dh61b936nxf40000gn/T/ipykernel_49088/3305441358.py:4: RuntimeWarning: invalid value encountered in divide
  A[m,:] = A[m,:]/diag #divide each component in row by diagonal component
/var/folders/zm/rgyh3v1x1vg4dh61b936nxf40000gn/T/ipykernel_49088/3305441358.py:5: RuntimeWarning: divide by zero encountered in scalar divide
  v[m]= v[m]/diag #divide row m in v by same value
/var/folders/zm/rgyh3v1x1vg4dh61b936nxf40000gn/T/ipykernel_49088/3305441358.py:5: RuntimeWarning: invalid value encountered in scalar divide
  v[m]= v[m]/diag #divide row m in v by same value


In [53]:
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)

for m in range(N):
    biggest_first = np.abs(A[m,m])
    biggest_first_row = m
    current_row = A[m,:].copy()
    current_row_v = v[m].copy()
    for j in range(m, N):
        if np.abs(A[j,m]) > biggest_first:
            biggest_first = np.abs(A[j,m])
            biggest_first_row = j
    #swap rows for A
    A[m,:] = A[biggest_first_row,:]
    A[biggest_first_row,:] = current_row
    #swap rows for v
    v[m] = v[biggest_first_row]
    v[biggest_first_row] = current_row_v
    
    diag = A[m,m] #diagonal component of row A
    A[m,:] = A[m,:]/diag #divide each component in row by diagonal component
    v[m]= v[m]/diag #divide row m in v by same value

    for i in range(m+1,N):
        first = A[i,m] #first nonzero element of each lower row
        A[i,:] -= first*A[m,:] #subtract appropriate multiple of top row from lower rows
        v[i] -= first*v[m]

#backsubstitution
for m in range(N-1,-1,-1): #3,2,1,0 for above matrix
    x[m] = v[m] #x[3] = v[3]
    for i in range(m+1, N): 
        x[m] = x[m] - A[m,i]*x[i] #for example x = v1 - a12y - a13z

print(x)

[[ 3.  4. -1. -1.]
 [ 0.  1.  4.  1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.          1.          4.          1.        ]
 [ 1.         -4.          1.          5.        ]
 [ 2.         -2.          1.          3.        ]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.          1.          4.          1.        ]
 [ 0.         -5.33333333  1.33333333  5.33333333]
 [ 0.         -4.66666667  1.66666667  3.66666667]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.         -5.33333333  1.33333333  5.33333333]
 [ 0.          1.          4.          1.        ]
 [ 0.         -4.66666667  1.66666667  3.66666667]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [-0.          1.         -0.25       -1.        ]
 [ 0.          1.          4.          1.        ]
 [ 0.         -4.66666667  1.66666667  3.66666667]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [-0.          1.         -0.25       -1.        ]
 

### LU Substitution 

Apply LU substitution to the same matrices 

In [54]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1], #using multiple brackets to create a proper 2d array
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.linalg.solve(A,v)

print(A)
print(x)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[ 2. -1. -2.  1.]


In [55]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)

v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.linalg.solve(A,v)

print(A)
print(x)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


**note** if want to perform LU decomposition separately from backsubtitution, can do so. Check out www.scipy.org to learn how to do so

In paricular, the Decompositions section of https://docs.scipy.org/doc/scipy/reference/linalg.html