# Class 12: Solving Linear Equations 

Ch. 6, section 1: Gaussian Elimination, Backsubstitution, Pivoting, & LU Decomposition    

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [2]:
import numpy as np

### Gaussian Elimination with backsubstitution 

Let's solve the example from the book: Use Gaussian Elimination to find $w, x, y,$ and $z$. 

$$\begin{pmatrix}
2 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [11]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [12]:
# gaussian elimination with backsubtitution 
for m in range(N):
    div = A[m, m]
    A[m,:] /= div
    v[m] /= div
    for i in range(m+1, N):
        mult = A[i,m]
        A[i,:] -=  mult*A[m,:]
        v[i] -= mult*v[m]
for m in range(N-1, -1, -1):
    x[m] = v[m]
    for i in range(m+1, N):
        x[m] -= A[m,i]*x[i]
print(x)

[ 2. -1. -2.  1.]


**note** this works for matrices of any size 

### Pivoting 

We need to interchange rows of the matrix for certain situations. Let's see an example below. 

$$\begin{pmatrix}
0 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [5]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


What happens when we run Gaussian Elimination on this system of equations? 

In [6]:
for m in range(N):
    div = A[m, m]
    A[m,:] /= div
    v[m] /= div
    for i in range(m+1, N):
        mult = A[i,m]
        A[i,:] -=  mult*A[m,:]
        v[i] -= mult*v[m]
for m in range(N-1, -1, -1):
    x[m] = v[m]
    for i in range(m+1, N):
        x[m] -= A[m,i]*x[i]
print(x)

[nan nan nan nan]


C:\Users\wesle\AppData\Local\Temp\ipykernel_12628\3928353241.py:3: RuntimeWarning: divide by zero encountered in divide
  A[m,:] /= div
C:\Users\wesle\AppData\Local\Temp\ipykernel_12628\3928353241.py:3: RuntimeWarning: invalid value encountered in divide
  A[m,:] /= div
C:\Users\wesle\AppData\Local\Temp\ipykernel_12628\3928353241.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  v[m] /= div
C:\Users\wesle\AppData\Local\Temp\ipykernel_12628\3928353241.py:4: RuntimeWarning: invalid value encountered in scalar divide
  v[m] /= div


In [8]:
for m in range(N):
    pivot = m
    largest = np.abs(A[m,m])
    for i in range(m+1, N):
        if np.abs(A[i,m]):
            

SyntaxError: expected ':' (1978722257.py, line 5)

### LU Substitution 

Apply LU substitution to the same matrices 

In [ ]:
#creates a number of matrices L, then multiplies them together, the product of which can be solved using backsubstitution
#this is efficient because it means we can calculate the matrices once and be done with it, which is the most time consuming part
#we could write this ourselves, but numpy has the .linalg module, which has a command 'solve' which does this all for us

In [7]:
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)
x = np.linalg.solve(A, v)
print(x)

[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


**note** if want to perform LU decomposition separately from backsubtitution, can do so. Check out www.scipy.org to learn how to do so

In paricular, the Decompositions section of https://docs.scipy.org/doc/scipy/reference/linalg.html