# Class 03: Basics of Python Programming 2

## Lists & Arrays 

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [2]:
import math
import numpy as np

In [12]:
#!python --version # note, here is how you check your python version if you ever need to in a Jupyter notebook 

### Let's talk through a couple if/while statements first! 

In [3]:
# if, else, and elif statements 
import random 

n = int(input("Choose a number between 1 and 100: "))
if n>100:
    print("you have chosen a number outside of the boundaries. Assigning number now.")
    n = random.randint(1, 101)
    print("your number is: ", n)
elif n < 1:
    print("you have chosen a number outside of the boundaries. Assigning number now.")
    n = random.randint(1, 101)
    print("your number is: ", n)
else: 
    print("your number is: ", n)

your number is:  6


In [4]:
x = -105

while x<0:
    print("x is less than 0")
    x = x+1
    print(x)
    if x == -100:
        break    
        
print("x is now ", x)

x is less than 0
-104
x is less than 0
-103
x is less than 0
-102
x is less than 0
-101
x is less than 0
-100
x is now  -100


##  Lists in Python

- Let's make a list - define 4 variables and make a list out of them 

In [5]:
a = 3
b = 15.4
c = "cat"
d = 1+2j
my_list = [a,b,c,d]
print(my_list)
print(type(my_list))

[3, 15.4, 'cat', (1+2j)]
<class 'list'>


 - now change the value of a in the cell below and then print the list again. What happens to the list? 

In [6]:
a = -22
print(my_list)
my_list[0]=-56.2
print(my_list)


[3, 15.4, 'cat', (1+2j)]
[-56.2, 15.4, 'cat', (1+2j)]


####  Indexing

-  reference certain components of a vector list to calculate magnitude:
    - Define the list r, containing information about the x, y, and z position of an object 
    - Calculate the magnitude of a vector pointing from the origin to point r

In [7]:
r = [2,5,8] #x,y,z position of an object in m

mag = math.sqrt(r[0]**2+r[1]**2+r[2]**2)
print(mag)

9.643650760992955


In [8]:
list_a = [1,2,3,4,5]
list_b = [6,7,8,9,10]
list_c = list_a+list_b
print(list_c)
list_d = list_b+list_a
print(list_d)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]


#### Operations on lists  

-  Define two lists, a and b, each consisting of 3 integers 
    - Add the two lists together, call it c, and print out
    - Now multipy c by 2
    - Print out the length of c
    - Append one additional number to the list c

In [9]:
a = [1,2,3]
b = [4,5,6]
c = a+b # "adding" = concatenating 
c *= 2 # multiply list c by 2
print(c)
print(len(c))
c.append(7)
print(c)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
12
[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 7]


####  Applying built-in mathematical operations to a list

- Find the average of the list abc below using any combination of the following built-in functions for lists: 
    sum(), max(), min(), len() 
- Print out the result 


- Create a new list that consists of the following: 
    - the first element of abc multipled by 2
    - the second element of abc multiplied by the third element
    - the third element of abc cubed and divided by the second element. 
- Print out your new list

In [10]:
abc = [1.0, 1.5, 2.2]
average_val = sum(abc)/len(abc)
print(average_val)

new_list = [abc[0]*2,round(abc[1]*abc[2],1),round(abc[2]**3/abc[1],3)]
print(new_list)

1.5666666666666667
[2.0, 3.3, 7.099]


## Arrays with Numpy


#### Creating arrays 

- Use Numpy to create an 2D array (5 rows, 2 columns) of zeros that are floats

In [16]:
arr_2D = np.zeros([5,2], float)
print(arr_2D)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


- Now create a 5 row, 2 column array using np.empty
    - What do you notice? 

In [17]:
emptyarr_2D = np.empty([5,2], int)
print(emptyarr_2D)

empty_arr = np.empty(5)
print(empty_arr)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[0.  0.5 1.  1.5 2. ]


- take the list below and convert it to an array 
- check the type of both the list and the array 

In [18]:
alist = [1,2,3,4,5]
print(alist)
print(type(alist))
a_array = np.array(alist)
print(a_array)
print(type(a_array))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


- Create an array abc and see what these do:

In [19]:
abc = a_array
abc = np.arange(9)
print(abc)

[0 1 2 3 4 5 6 7 8]


In [ ]:
print(abc.ndim)
print(abc.shape)
print(abc.size)
print(abc.dtype)
print(abc.itemsize)
print(type(abc))
help(abc)

- Print xarray from the class notes. How does arange work? 
    

In [ ]:
xarray = np.arange(0,16,5,float) # note that if I wanted to include 15, needed to go up to 16, which is not included 
print(xarray)
print(type(xarray))

[ 0.  5. 10. 15.]
<class 'numpy.ndarray'>


- Create a 2D array (arr2d) with 15 numbers in it
- reshape it to a 2D array that is 3 rows by 5 columns 
- change the 0 to a 42 & 105 to 999

In [21]:
arr2d = np.arange(0,216,15).reshape(3,5)
print(arr2d)

arr2d[0,0]=42
arr2d[1,2] = 999
print(arr2d)

[[  0  15  30  45  60]
 [ 75  90 105 120 135]
 [150 165 180 195 210]]
[[ 42  15  30  45  60]
 [ 75  90 999 120 135]
 [150 165 180 195 210]]


#### Arithmetic with arrays 
Try the following:
- divide a arr2D by itself
- add arr2D to itself 

In [22]:
new_arr = arr2d/arr2d
print(new_arr)
otherarr = arr2d+arr2d
print(otherarr)
otherarr = np.sqrt(arr2d)
print(otherarr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[  84   30   60   90  120]
 [ 150  180 1998  240  270]
 [ 300  330  360  390  420]]
[[ 6.4807407   3.87298335  5.47722558  6.70820393  7.74596669]
 [ 8.66025404  9.48683298 31.60696126 10.95445115 11.61895004]
 [12.24744871 12.84523258 13.41640786 13.96424004 14.49137675]]


#### Loading in data from text file 
- Download numbers.txt and numbers2D.txt from Moodle or the book website 
- print both out to see what they look like
- print the element from numbers2D that is in the third row and second column 

In [ ]:
a_arr = np.loadtxt("numbers.txt", float) # note these files have to be in the same location as your .ipynb file 
b_arr = np.loadtxt("numbers2D.txt", float)
print(a_arr)
print(b_arr)
print(b_arr[2,1])
print(b_arr.shape)

[ 2.  -1.5  4.   9.2  8.  70.6 16.  32. ]
[[  2.    4. ]
 [ -1.5  -3. ]
 [  4.    8. ]
 [  9.2  18.4]
 [  8.   16. ]
 [ 70.6 141.2]
 [ 16.   32. ]
 [ 32.   64. ]]
8.0
(8, 2)


#### Mathematical functions on arrays 
- Define a new array that is the absolute value of the numbers2D array 
- Define a new array that is the square root of the numbers2D array

In [24]:
newb_arr = np.absolute(b_arr)
print(newb_arr)
c_arr = np.sqrt(newb_arr)
print(c_arr)

[[  2.    4. ]
 [  1.5   3. ]
 [  4.    8. ]
 [  9.2  18.4]
 [  8.   16. ]
 [ 70.6 141.2]
 [ 16.   32. ]
 [ 32.   64. ]]
[[ 1.41421356  2.        ]
 [ 1.22474487  1.73205081]
 [ 2.          2.82842712]
 [ 3.03315018  4.28952212]
 [ 2.82842712  4.        ]
 [ 8.40238062 11.88276062]
 [ 4.          5.65685425]
 [ 5.65685425  8.        ]]


#### Copying arrays 
- Use np.copy to make a copy of the numbers2D array
- replace one of the elemnts in the copy array and print back out both arrays 

In [25]:
copy_arr = b_arr
real_copy = np.copy(b_arr)
copy_arr[3,0] = -99.99
real_copy[3,0] = 2000
print(b_arr)
print(copy_arr)
print(real_copy)

[[  2.     4.  ]
 [ -1.5   -3.  ]
 [  4.     8.  ]
 [-99.99  18.4 ]
 [  8.    16.  ]
 [ 70.6  141.2 ]
 [ 16.    32.  ]
 [ 32.    64.  ]]
[[  2.     4.  ]
 [ -1.5   -3.  ]
 [  4.     8.  ]
 [-99.99  18.4 ]
 [  8.    16.  ]
 [ 70.6  141.2 ]
 [ 16.    32.  ]
 [ 32.    64.  ]]
[[ 2.000e+00  4.000e+00]
 [-1.500e+00 -3.000e+00]
 [ 4.000e+00  8.000e+00]
 [ 2.000e+03  1.840e+01]
 [ 8.000e+00  1.600e+01]
 [ 7.060e+01  1.412e+02]
 [ 1.600e+01  3.200e+01]
 [ 3.200e+01  6.400e+01]]


### <font color='purple'> Sets & Dictionaries </font> 

Here is an example set made from a list: 

In [ ]:
# We will do this next time! 

To create an example dictionary, let's say that I have the following data:
- voltage = 2 V, 4 V, 6 V
- current = 1 A, 2 A, 3 A
- uncertainty in voltage = 0.05 V for all 

Below we will: 
- Make the dictionary based on these values and keys
- Add the key and elements: resistance = 2.0 ohms for all 
- list the keys & dictionary 
- print out the second element of one of the key arrays in the dictionary 

In [ ]:
# We will do this next time! 