# Class 12: Solving Linear Equations 

Ch. 6, section 1: Gaussian Elimination, Backsubstitution, Pivoting, & LU Decomposition    

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [1]:
import numpy as np

### Gaussian Elimination with backsubstitution 

Let's solve the example from the book: Use Gaussian Elimination to find $w, x, y,$ and $z$. 

$$\begin{pmatrix}
2 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [2]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [3]:
# gaussian elimination with backsubtitution 
for m in range(N): 
    # divide by diagonal elements 
    div = A[m,m]
    A[m,:] /= div 
    v[m] /= div
    
    # subtract from lower rows 
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# apply backsubtitution 
for m in range(N-1,-1,-1): 
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

In [4]:
print(x)

[ 2. -1. -2.  1.]


**note** this works for matrices of any size 

### Pivoting 

We need to interchange rows of the matrix for certain situations. Let's see an example below. 

$$\begin{pmatrix}
0 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [19]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


What happens when we run Gaussian Elimination on this system of equations? 

In [6]:
# gaussian elimination with backsubtitution 
for m in range(N): 
    # divide by diagonal elements 
    div = A[m,m]
    A[m,:] /= div 
    v[m] /= div
    
    # subtract from lower rows 
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# apply backsubtitution 
for m in range(N-1,-1,-1): 
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)

[nan nan nan nan]


/var/folders/_7/3rpl5gcd2bg758cn3lr13thn8wg2tc/T/ipykernel_59000/1277883334.py:5: RuntimeWarning: divide by zero encountered in divide
  A[m,:] /= div
/var/folders/_7/3rpl5gcd2bg758cn3lr13thn8wg2tc/T/ipykernel_59000/1277883334.py:5: RuntimeWarning: invalid value encountered in divide
  A[m,:] /= div
/var/folders/_7/3rpl5gcd2bg758cn3lr13thn8wg2tc/T/ipykernel_59000/1277883334.py:6: RuntimeWarning: divide by zero encountered in scalar divide
  v[m] /= div
/var/folders/_7/3rpl5gcd2bg758cn3lr13thn8wg2tc/T/ipykernel_59000/1277883334.py:6: RuntimeWarning: invalid value encountered in scalar divide
  v[m] /= div


In [20]:
# pivoting 
for m in range(N):
    # find the row with the largest pivot element 
    pivot = m
    largest = np.abs(A[m,m])
    for i in range(m+1,N):
        if np.abs(A[i,m]) > largest:
            largest = np.abs(A[i,m])
            pivot = i
    
    # swap rows
    for i in range(N):
        A[m,i], A[pivot,i] = A[pivot,i], A[m,i]
    v[m],v[pivot] = v[pivot], v[m]

    # gaussian elimination with backsubtitution 
    for m in range(N): 
        # divide by diagonal elements 
        div = A[m,m]
        A[m,:] /= div 
        v[m] /= div
        
        # subtract from lower rows 
        for i in range(m+1,N):
            mult = A[i,m]
            A[i,:] -= mult*A[m,:]
            v[i] -= mult*v[m]

# apply backsubtitution 
for m in range(N-1,-1,-1): 
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)

[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


### LU Substitution 

Apply LU substitution to the same matrices 

In [9]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.linalg.solve(A,v)
print(x)



[ 2. -1. -2.  1.]


In [13]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.linalg.solve(A,v)
print(x)

[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


**note** if want to perform LU decomposition separately from backsubtitution, can do so. Check out www.scipy.org to learn how to do so

In paricular, the Decompositions section of https://docs.scipy.org/doc/scipy/reference/linalg.html