# Class 12: Solving Linear Equations 

Ch. 6, section 1: Gaussian Elimination, Backsubstitution, Pivoting, & LU Decomposition    

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [1]:
import numpy as np

### Gaussian Elimination with backsubstitution 

Let's solve the example from the book: Use Gaussian Elimination to find $w, x, y,$ and $z$. 

$$\begin{pmatrix}
2 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [64]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x

print(A)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [65]:
# gaussian elimination with backsubtitution 
def Gaussian_Elimination(A,v):
    N = len(v)
    for m in range(N):
        factor = A[m,m]
        
        A[m,:] /= factor
        v[m] /= factor
        for i in range(m+1,N):
            factor = A[i,m]
            A[i,:] -= factor*A[m,:]
            v[i] -= factor*v[m]
    return A,v
A,v = Gaussian_Elimination(A,v)
print(A)
print(v)
def Backward_Substitution(A,v):
    N = len(v)
    x = np.zeros(N, float)
    for m in range(N-1,-1,-1):
        x[m]=v[m]
        for i in range(m+1,N):
            x[m] -= A[m,i]*x[i]
    return x
x = Backward_Substitution(A,v)
print(x)

[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
[-2.   3.6 -2.   1. ]
[ 2. -1. -2.  1.]


**note** this works for matrices of any size 

### Pivoting 

We need to interchange rows of the matrix for certain situations. Let's see an example below. 

$$\begin{pmatrix}
0 & 1  & 4  & 1  \\
3 & 4  & -1 & -1 \\
1 & -4 & 1  & 5  \\
2 & -2 & 1  & 3  
\end{pmatrix} 
\begin{pmatrix}
w \\
x \\
y \\
z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3  \\
9  \\
7  
\end{pmatrix}$$

In [39]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.zeros(N, float)
print(A)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


What happens when we run Gaussian Elimination on this system of equations? 

In [42]:
def Pivot(A):
    N = len(A)
    for m in range(N):
        pivot,largest = m,np.abs(A[m,m])
        for i in range(m+1,N):
            if np.abs(A[i,m])>largest:
                pivot, largest = i,np.abs(A[i,m])
        for i in range(N):
            A[m,i], A[pivot,i] = A[pivot,i],A[m,i]
    return A
Gaussian_Elimination(Pivot(A),v)

(array([[ 1.        ,  1.33333333, -0.33333333, -0.33333333],
        [ 0.        ,  1.        , -0.25      , -1.        ],
        [ 0.        ,  0.        ,  1.        ,  0.47058824],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([-1.33333333,  0.        ,  0.        , 16.05555556]))

### LU Substitution 

Apply LU substitution to the same matrices 

In [51]:
# define matrix & vectors 
A = np.array([[2, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
x = np.linalg.solve(A,v)
print(x)

[ 2. -1. -2.  1.]


In [67]:
# define matrix & vectors 
A = np.array([[0, 1,  4,  1],
             [3, 4, -1, -1],
             [ 1, -4, 1,  5], 
             [ 2, -2, 1,  3]], float)
v = np.array([-4, 3, 9, 7], float)

# determine the number of variables solving for
N = len(v)
# create array for results, x
inv = np.linalg.inv(A)
x = np.linalg.solve(A,v)
print(x)
print(np.linalg.matmul(inv,v))


[ 1.61904762 -0.42857143 -1.23809524  1.38095238]
[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


**note** if want to perform LU decomposition separately from backsubtitution, can do so. Check out www.scipy.org to learn how to do so

In paricular, the Decompositions section of https://docs.scipy.org/doc/scipy/reference/linalg.html