# Class 03: Basics of Python Programming 2

## Lists & Arrays 

- Complete the activities as instructed by the professor

#### Import any packages we need below (update as we go):

In [2]:
import math as m
import numpy as np

### Let's talk through a couple if/while statements first! 

In [ ]:
# if, else, and elif statements 
import random 

n = int(input("Choose a number between 1 and 100: "))
if n>100:
    print("you have chosen a number outside of the boundaries. Assigning number now.")
    n = random.randint(1, 101)
    print("your number is: ", n)
elif n < 1:
    print("you have chosen a number outside of the boundaries. Assigning number now.")
    n = random.randint(1, 101)
    print("your number is: ", n)
else: 
    print("your number is: ", n)

In [ ]:
x = -105

while x<0:
    print("x is less than 0")
    x = x+1
    print(x)
    if x == -100:
        break    
        
print("x is now ", x)

##  Lists in Python

- Let's make a list - define 4 variables and make a list out of them 

In [3]:
a = "Bob Evans"
b = 5
c = 5.0
d = "Evan Bobs"
List = [a,b,c,d]
print(List)

['Bob Evans', 5, 5.0, 'Evan Bobs']


 - now change the value of a in the cell below and then print the list again. What happens to the list? 

In [6]:
List[3] = "Bob Evans"
print(List)

['Bob Evans', 5, 5.0, 'Bob Evans']


####  Indexing

-  reference certain components of a vector list to calculate magnitude:
    - Define the list r, containing information about the x, y, and z position of an object 
    - Calculate the magnitude of a vector pointing from the origin to point r

In [9]:
x=float(input("What is the x-position?")) #x-position
y=float(input("What is the y-position?")) #y-position
z=float(input("What is the z-position?")) #z-position
R = [x,y,z] #(x,y,z)
magnitude = m.sqrt(R[0]**2 + R[1]**2 + R[2]**2)
print(magnitude)

1.7320508075688772


#### Operations on lists  

-  Define two lists, a and b, each consisting of 3 integers 
    - Add the two lists together, call it c, and print out
    - Now multipy c by 2
    - Print out the length of c
    - Append one additional number to the list c

In [26]:
a = [1,2,3]
b = [6,5,4]
c = a + b
print(c)
c *= 2
print(len(c))
c.append(0)
print(c)

[1, 2, 3, 6, 5, 4]
12
[1, 2, 3, 6, 5, 4, 1, 2, 3, 6, 5, 4, 0]


####  Applying built-in mathematical operations to a list

- Find the average of the list abc below using any combination of the following built-in functions for lists: 
    sum(), max(), min(), len() 
- Print out the result 


- Create a new list that consists of the following: 
    - the first element of abc multipled by 2
    - the second element of abc multiplied by the third element
    - the third element of abc cubed and divided by the second element. 
- Print out your new list

In [36]:
abc = [1.0, 1.5, 2.2]
Total = sum(abc)
Count = len(abc)
Average = Total/Count
print(Average)
List = list(abc)
List[0] = 2*abc[0]
List[1] = abc[1]*abc[2]
List[2] = abc[2]**3/abc[1]
print(abc)

1.5666666666666667
[1.0, 1.5, 2.2]


## Arrays with Numpy


#### Creating arrays 

- Use Numpy to create an 2D array (5 rows, 2 columns) of zeros that are floats

In [39]:
array_zero = np.zeros([5,2],float)
print(array_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


- Now create a 5 row, 2 column array using np.empty
    - What do you notice? 

In [65]:
array_empty = np.empty([5,2])
print(array_empty)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


- take the list below and convert it to an array 
- check the type of both the list and the array 

In [67]:
alist = [1,2,3,4,5]
a_array = np.array(alist,int)
print(alist)
print(type(alist))
print(a_array)
print(type(a_array))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


- Create an array abc and see what these do:

In [ ]:
abc = 

In [ ]:
print(abc.ndim)
print(abc.shape)
print(abc.size)
print(abc.dtype)
print(abc.itemsize)
print(type(abc))
help(abc)

- Print xarray from the class notes. How does arange work? 
    

- Create a 2D array (arr2d) with 15 numbers in it
- reshape it to a 2D array that is 3 rows by 5 columns 
- change the 0 to a 42 & 105 to 999

#### Arithmetic with arrays 
Try the following:
- divide a arr2D by itself
- add arr2D to itself 

#### Loading in data from text file 
- Download numbers.txt and numbers2D.txt from Moodle or the book website 
- print both out to see what they look like
- print the element from numbers2D that is in the third row and second column 

#### Mathematical functions on arrays 
- Define a new array that is the absolute value of the numbers2D array 
- Define a new array that is the square root of the numbers2D array

#### Copying arrays 
- Use np.copy to make a copy of the numbers2D array
- replace one of the elemnts in the copy array and print back out both arrays 

### <font color='purple'> Sets & Dictionaries </font> 

Here is an example set made from a list: 

To create an example dictionary, let's say that I have the following data:
- voltage = 2 V, 4 V, 6 V
- current = 1 A, 2 A, 3 A
- uncertainty in voltage = 0.05 V for all 

Below we will: 
- Make the dictionary based on these values and keys
- Add the key and elements: resistance = 2.0 ohms for all 
- list the keys & dictionary 
- print out the second element of one of the key arrays in the dictionary 